/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __CLK_COMMON_H__
#define __CLK_COMMON_H__

#include <osal/hal_time.h>

#include "../platform/platform_common.h"

enum clk_ret_code
{
	CLK_RET_OK = 0,
	CLK_RET_INVALID_PARAMETER = -5000,
	CLK_RET_INVALID_CLK,
	CLK_RET_INVALID_CLK_HW,
	CLK_RET_INVALID_RST_HW,
	CLK_RET_INVALID_CLK_ID,
	CLK_RET_INVALID_CLK_CONTROLLER_ID,
	CLK_RET_INVALID_RST_ID,
	CLK_RET_INVALID_RST_CONTROLLER_ID,
	CLK_RET_INVALID_STRUCT_FIELD_VALUE,
	CLK_RET_CODE_INIT_LOCK_FAILED,
	CLK_RET_INVALID_PARENT_NUM,
	CLK_RET_INVALID_PARENT_ARRAY,
	CLK_RET_INVALID_PARENT_INDEX,
	CLK_RET_PARENT_NOT_EXIST,
	CLK_RET_PARENT_NOT_FOUND,
	CLK_RET_WRONG_SINGLE_PARENT,
	CLK_RET_WRONG_PARENT,
	CLK_RET_OPS_NOT_EXIST_WITH_MULTI_PARENT,

	/* usage fault */
	CLK_RET_CLK_SRC_CAN_NOT_SET_PARENT,
	CLK_RET_CLK_SRC_HAVE_NO_PARENT,
	CLK_RET_CLK_SRC_CAN_NOT_SET_FREQ,
	CLK_RET_CLK_NOT_SUPPORT_SET_FREQ,

	CLK_RET_CONTROLLER_NOT_FOUND,
	CLK_RET_CLK_HW_NOT_EXIST,
	CLK_RET_INVALID_GATE_BIT_OFFSET,
	CLK_RET_INVALID_CTRL_BIT_OFFSET,
	CLK_RET_INVALID_CTRL_FIELD_OFFSET,
	CLK_RET_INVALID_CTRL_FIELD_WIDTH,
	CLK_RET_INVALID_CTRL_FIELD_INFO,
	CLK_RET_CTRL_FIELD_WIDTH_EXCEED_SW_LIMIT,

	CLK_RET_CLK_FREQ_EXCEED_UPPER_LIMIT,

	CLK_RET_TARGET_FREQ_NOT_AVAILABLE,
	CLK_RET_TARGET_FREQ_GREATER_THAN_PARENT_FREQ,
	CLK_RET_TARGET_FREQ_LESS_THAN_PARENT_FREQ,

	CLK_RET_INVALID_DIV_VAR_TYPE,
	CLK_RET_DIV_MAP_NOT_EXIST_IN_VARIANT,
	CLK_RET_DIV_MAP_FIELD_VALUE_EXCEED_UPPER_LIMIT,

	CLK_RET_DIV_VAL_IS_ZERO,
	CLK_RET_DIV_VAL_NOT_FOUND_IN_MAP,
	CLK_RET_DIV_VAL_IS_NOT_POWER_OF_TWO,
	CLK_RET_DIV_VAL_EXCEED_UPPER_LIMIT,
	CLK_RET_DIV_VAR_TYPE_NOT_SUPPORTED,
	//CLK_RET_GET_DIV_VAL_FAILED,
	//CLK_RET_INCORRECT_TARGET_FREQ,
	CLK_RET_MULT_VAL_IS_ZERO,
	CLK_RET_MULT_VAL_EXCEED_UPPER_LIMIT,
	CLK_RET_MULT_VAR_TYPE_NOT_SUPPORTED,

	CLK_RET_PLL_VAR_TYPE_NOT_SUPPORTED,
	CLK_RET_PLL_WAIT_STABLE_TIMEOUT,

	CLK_RET_FIELD_VALUE_EXCEED_UPPER_LIMIT,
	CLK_RET_FIELD_VALUE_NOT_FOUND_IN_MAP,

	CLK_RET_FIELD_VALUE_NOT_FOUND_FOR_TARGET_FREQ,

	CLI_RET_INVALID_DIV_ID_IN_LINK_TYPE,
	CLK_RET_CLK_HW_NOT_EXIST_IN_LINK_TYPE,
	CLK_RET_LINK_TYPE_NOT_SUPPORTED,
	CLK_RET_DIV_LINK_TYPE_NOT_SUPPORTED,
};

typedef enum clk_ret_code hal_clk_status_t;

#define clk_udelay hal_udelay

typedef uint8_t clk_controller_id_t;
typedef uint16_t clk_id_t;


typedef clk_controller_id_t hal_clk_type_t;
typedef clk_id_t hal_clk_id_t;

typedef void * hal_clk_t;


#define SYS_CLK_CONTROLLER_NUMBER PLAT_CLK_CONTROLLER_NUMBER
#define SYS_CLK_SRC_CONTROLLER_ID PLAT_CLK_SRC_CONTROLLER_ID
#define SYS_CLK_SRC_NUMBER PLAT_CLK_SRC_NUMBER


#define MAX_CLK_CTRL_REG_BITS 32
#define MAX_RST_CTRL_REG_BITS 32

#define MAX_CONTROL_BIT_OFFSET 31
#define CTRL_BIT_ABSENT_BIT_OFFSET 63

#endif /* __CLK_COMMON_H__ */

