/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
* Copyright (c) 2021-2027 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY¡¯S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS¡¯SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY¡¯S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __TWI_SUN55IW6_H__
#define __TWI_SUN55IW6_H__

#if defined(CONFIG_ARCH_RISCV)
#define SUNXI_IRQ_TWI0		MAKE_IRQn(26, 0)
#define SUNXI_IRQ_TWI1		MAKE_IRQn(27, 0)
#define SUNXI_IRQ_TWI2		MAKE_IRQn(28, 0)
#define SUNXI_IRQ_TWI3		MAKE_IRQn(29, 0)
#define SUNXI_IRQ_TWI4		MAKE_IRQn(30, 0)
#define SUNXI_IRQ_TWI5		MAKE_IRQn(31, 0)
#define SUNXI_IRQ_TWI6		MAKE_IRQn(171, 0)
#define SUNXI_IRQ_S_TWI0	MAKE_IRQn(223, 0)
#define SUNXI_IRQ_S_TWI1	MAKE_IRQn(224, 0)
#else
#define SUNXI_IRQ_TWI0          10
#define SUNXI_IRQ_TWI1          11
#define SUNXI_IRQ_TWI2          12
#define SUNXI_IRQ_TWI3          13
#define SUNXI_IRQ_TWI4          14
#define SUNXI_IRQ_TWI5          15
#define SUNXI_IRQ_TWI6          155
#define SUNXI_IRQ_S_TWI0        207
#define SUNXI_IRQ_S_TWI1        208
#endif

/** the base address of TWI*/
#define SUNXI_TWI0_PBASE	0x02510000
#define SUNXI_TWI1_PBASE	0x02511000
#define SUNXI_TWI2_PBASE	0x02512000
#define SUNXI_TWI3_PBASE	0x02513000
#define SUNXI_TWI4_PBASE	0x02514000
#define SUNXI_TWI5_PBASE	0x02515000
#define SUNXI_TWI6_PBASE	0x02516000
#define SUNXI_S_TWI0_PBASE	0x07083000
#define SUNXI_S_TWI1_PBASE	0x07084000

#define TWI0_PIN_MUXSEL 2
#define TWI1_PIN_MUXSEL 2
#define TWI2_PIN_MUXSEL 3
#define TWI3_PIN_MUXSEL 2
#define TWI4_PIN_MUXSEL 3
#define TWI5_PIN_MUXSEL 3
#define TWI6_PIN_MUXSEL 2
#define S_TWI0_PIN_MUXSEL 2
#define S_TWI1_PIN_MUXSEL 2
#define TWI_DISABLE_PIN_MUXSEL 15
#define TWI_PULL_STATE 1
#define TWI_DRIVE_STATE 0

#define TWI0_SCK GPIOH(0)
#define TWI0_SDA GPIOH(1)
#define TWI1_SCK GPIOH(2)
#define TWI1_SDA GPIOH(3)
#define TWI2_SCK GPIOI(15)
#define TWI2_SDA GPIOI(16)
#define TWI3_SCK GPIOI(11)
#define TWI3_SDA GPIOI(12)
#define TWI4_SCK GPIOJ(24)
#define TWI4_SDA GPIOJ(25)
#define TWI5_SCK GPIOJ(26)
#define TWI5_SDA GPIOJ(27)
#define TWI6_SCK GPIOE(16)
#define TWI6_SDA GPIOE(17)
#define S_TWI0_SCK GPIOL(0)
#define S_TWI0_SDA GPIOL(1)
#define S_TWI1_SCK GPIOL(8)
#define S_TWI1_SDA GPIOL(9)

#define SUNXI_TWI_CLK_TYPE HAL_SUNXI_R_CCU
#define SUNXI_TWI_RESET_TYPE HAL_SUNXI_R_RESET

#define SUNXI_CLK_TWI(x)	CLK_TWI##x
#define SUNXI_CLK_RST_TWI(x)	RST_BUS_TWI##x
#define SUNXI_R_CLK_TWI(x)	CLK_R_TWI##x
#define SUNXI_R_CLK_RST_TWI(x)	RST_BUS_R_TWI##x

#endif /* __TWI_SUN55IW6_H__ */

