/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __DMA_SUN60IW1_H__
#define __DMA_SUN60IW1_H__

#if defined(CONFIG_ARCH_DSP)
#define DMA0
#define DMA_IRQ_NUM		RINTC_IRQ_MASK | 21	/* MCU DMA 0~7 channel irq non-secure */
#define DMA_SECURE_IRQ_NUM	RINTC_IRQ_MASK | 22	/* MCU DMA 0~7 channel irq secure */
#define NR_MAX_CHAN		 8	/* total of channels */
#define START_CHAN_OFFSET        0
#define SUNXI_CLK_DMA            CLK_DMA_HCLK
#define SUNXI_CLK_MBUS_DMA       CLK_DMA_MCLK
#define SUNXI_RST_DMA            RST_BUS_DSP_DMA
#endif


#if defined(DMA0)
#define SUNXI_DMAC_PBASE	(0x07150000ul)
#endif

#define DMA_IRQ_V2
#define DMA_IRQ_EN(x)		(SUNXI_DMAC_PBASE + (0x134 + ((x + START_CHAN_OFFSET) << 6)))
#define DMA_IRQ_STAT(x)		(SUNXI_DMAC_PBASE + (0x138 + ((x + START_CHAN_OFFSET) << 6)))
/*
 * The source DRQ type and port corresponding relation
 */
#define DRQSRC_SDRAM		0
#define DRQSRC_DRAM		1
#define DRQSRC_UART0_RX  	2
#define DRQSRC_UART1_RX  	3
#define DRQSRC_TWI0_RX		4
#define DRQSRC_TWI1_RX		5
#define DRQSRC_TWI2_RX		6
#define DRQSRC_R_SPI		7
#define DRQSRC_R_I2S0_RX	8
#define DRQSRC_R_DMAIC		9
#define DRQSRC_UART2_RX		10

/*
 * The destination DRQ type and port corresponding relation
 */
#define DRQDST_SDRAM		0
#define DRQDST_DRAM		1
#define DRQDST_UART0_TX  	2
#define DRQDST_UART1_TX  	3
#define DRQDST_TWI0_TX		4
#define DRQDST_TWI1_TX		5
#define DRQDST_TWI2_TX		6
#define DRQDST_R_SPI		7
#define DRQDST_R_I2S0_TX	8
#define DRQDST_UART2_TX		10

#endif /*__DMA_SUN20IW2_H__  */
