/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __DMA_SUN55IW3_H__
#define __DMA_SUN55IW3_H__

#if defined(CONFIG_CORE_DSP0)
#define SUNXI_DMAC_PBASE	(0x07121000ul)
#define DMA_IRQ_NUM		(9)	/* MCU DMA1 channel irq non-secure to mcu */
#define SUNXI_USED_DMA1 	1
#endif

#if defined(CONFIG_ARCH_RISCV_E906)
#define SUNXI_USED_DMA0		1
#define SUNXI_DMAC_PBASE	(0x03002000ul)
#define DMA_IRQ_NUM		(MAKE_IRQn(88, 0))
#endif

#define NR_MAX_CHAN		16	/* total of channels */
#define START_CHAN_OFFSET       0
#define DMA_START_CHAN		8

#define SUNXI_CLK_DMA CLK_BUS_MCU_DMA
#define SUNXI_CLK_MBUS_DMA CLK_BUS_MCU_DMA_MBUS
#define SUNXI_RST_DMA RST_BUS_MCU_DMA
#define SUNXI_MCU_CLK CLK_BUS_MCU_MBUS

/*
 * The IRQ control for cpu and mcu
 */
#define SUNXI_IRQ_CONTROL 	        1
#define SUNXI_CPU_IRQ_CONTROL_VAL 	0xFF
#define SUNXI_MCU_IRQ_CONTROL_VAL 	0xFF00
#define SUNXI_CPU_IRQ_CONTROL_OFFSET 	(SUNXI_DMAC_PBASE + 0x34)
#define SUNXI_MCU_IRQ_CONTROL_OFFSET 	(SUNXI_DMAC_PBASE + 0x38)

#if defined(SUNXI_USED_DMA1)
/*
 * The source DRQ type and port corresponding relation
 */
#define DRQSRC_SRAM		0
#define DRQSRC_SDRAM		1
#define DRQSRC_OWA		2
#define DRQSRC_I2S0_RX		3
#define DRQSRC_I2S1_RX		4
#define DRQSRC_I2S2_RX		5
#define DRQSRC_I2S3_RX		6
#define DRQSRC_AUDIO_CODEC	7
#define DRQSRC_DMIC		8
#define DRQSRC_TWI0_RX		9
#define DRQSRC_TWI1_RX		10
#define DRQSRC_UART0_RX		11
#define DRQSRC_UART1_RX		12
#define DRQSRC_R_SPI_RX		13
#define DRQSRC_TWI2_RX		14

/*
 * The destination DRQ type and port corresponding relation
 */
#define DRQDST_SRAM		0
#define DRQDST_SDRAM		1
#define DRQDST_OWA		2
#define DRQDST_I2S0_TX		3
#define DRQDST_I2S1_TX		4
#define DRQDST_I2S2_TX		5
#define DRQDST_I2S3_TX		6
#define DRQDST_AUDIO_CODEC	7
#define DRQDST_DMIC		8
#define DRQDST_TWI0_TX		9
#define DRQDST_TWI1_TX		10
#define DRQDST_UART0_TX		11
#define DRQDST_UART1_TX		12
#define DRQDST_R_SPI_TX		13
#define DRQDST_TWI2_TX		14

#elif defined(SUNXI_USED_DMA0)
/*
 * The source DRQ type and port corresponding relation
 */
#define DRQSRC_SRAM		0
#define DRQSRC_SDRAM		1
#define DRQSRC_NAND		10
#define DRQSRC_GPADC		12
#define DRQSRC_GPADC1		13
#define DRQSRC_UART0_RX		14
#define DRQSRC_UART1_RX		15
#define DRQSRC_UART2_RX		16
#define DRQSRC_UART3_RX		17
#define DRQSRC_UART4_RX		18
#define DRQSRC_UART5_RX		19
#define DRQSRC_UART6_RX		20
#define DRQSRC_UART7_RX		21
#define DRQSRC_SPI0_RX		22
#define DRQSRC_SPI1_RX		23
#define DRQSRC_SPI2_RX		24
#define DRQSRC_OTG0_EP1		30
#define DRQSRC_OTG0_EP2		31
#define DRQSRC_OTG0_EP3		32
#define DRQSRC_OTG0_EP4		33
#define DRQSRC_OTG0_EP5		34
#define DRQSRC_TWI0_RX		43
#define DRQSRC_TWI1_RX		44
#define DRQSRC_TWI2_RX		45
#define DRQSRC_TWI3_RX		46
#define DRQSRC_TWI4_RX		47
#define DRQSRC_TWI5_RX		48
#define DRQSRC_R_TWI0_RX	49
#define DRQSRC_R_TWI1_RX	50
#define DRQSRC_R_UART0_RX	51
#define DRQSRC_R_UART1_RX	52
#define DRQSRC_R_SPI_RX		53

/*
 * The destination DRQ type and port corresponding relation
 */
#define DRQDST_SRAM		0
#define DRQDST_SDRAM		1
#define DRQDST_NAND		10
#define DRQDST_GPADC		12
#define DRQDST_GPADC1		13
#define DRQDST_UART0_TX		14
#define DRQDST_UART1_TX		15
#define DRQDST_UART2_TX		16
#define DRQDST_UART3_TX		17
#define DRQDST_UART4_TX		18
#define DRQDST_UART5_TX		19
#define DRQDST_UART6_TX		20
#define DRQDST_UART7_TX		21
#define DRQDST_SPI0_TX		22
#define DRQDST_SPI1_TX		23
#define DRQDST_SPI2_TX		24
#define DRQDST_OTG0_EP1		30
#define DRQDST_OTG0_EP2		31
#define DRQDST_OTG0_EP3		32
#define DRQDST_OTG0_EP4		33
#define DRQDST_OTG0_EP5		34
#define DRQDST_TWI0_TX		43
#define DRQDST_TWI1_TX		44
#define DRQDST_TWI2_TX		45
#define DRQDST_TWI3_TX		46
#define DRQDST_TWI4_TX		47
#define DRQDST_TWI5_TX		48
#define DRQDST_R_TWI0_TX	49
#define DRQDST_R_TWI1_TX	50
#define DRQDST_R_UART0_TX	51
#define DRQDST_R_UART1_TX	52
#define DRQDST_R_SPI_TX		53
#endif

#endif/*__DMA_SUN55IW3_H__  */
