/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/* this file is generate by ./mk_event_def.sh, should not be modify directly */
#ifndef _TRACE_EVENT_DEF_H_
#define _TRACE_EVENT_DEF_H_

typedef enum {
	EV_SYS,
	EV_RT_SYS,
	EV_TICK,
	EV_IRQ,
	EV_MEM,
	EV_SCHE,
	EV_RT_TMR,
	EV_MUTEX,
	EV_SPIN,
	EV_SEM,
	EV_RT_NOTIFY,
	EV_QUEUE,
	EV_RT_QUEUE,
	EV_FS,
	EV_FATFS,
	EV_NTFS,
	EV_OPENAMP,
	EV_SUNXIAMP,
	EV_USR0,
	EV_RPD,
	EV_NUM_SUBSYS
} event_subsys;

#define EV_SYS_STRING                  "sys"
#define EV_RT_SYS_STRING               "rt_sys"
#define EV_TICK_STRING                 "tick"
#define EV_IRQ_STRING                  "irq"
#define EV_MEM_STRING                  "mem"
#define EV_SCHE_STRING                 "sche"
#define EV_RT_TMR_STRING               "rt-timer"
#define EV_MUTEX_STRING                "mutex"
#define EV_SPIN_STRING                 "spin"
#define EV_SEM_STRING                  "sem"
#define EV_RT_NOTIFY_STRING            "notify"
#define EV_QUEUE_STRING                "queue"
#define EV_RT_QUEUE_STRING             "rt_queue"
#define EV_FS_STRING                   "fs"
#define EV_FATFS_STRING                "fatfs"
#define EV_NTFS_STRING                 "ntfs"
#define EV_OPENAMP_STRING              "amp"
#define EV_SUNXIAMP_STRING             "amp"
#define EV_USR0_STRING                 "usr0"
#define EV_RPD_STRING                  "rpd"

#endif
