/*
 * for clk
 */

#ifndef __CCMU_AON_H
#define __CCMU_AON_H

#include <arch/sun300iw1/clock_autogen_aon.h>

#define SUNXI_CCM_AON_BASE SUNXI_CCU_AON_BASE
/* pll list */

#define CCMU_PLL_PERI0_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL0_REG)
#define CCMU_PLL_PERI1_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL1_REG)
#define CCMU_PLL_DDR0_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_DDR_CTRL_REG)
#define CCMU_PLL_PERI_PAT0_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_PAT0_CTRL_REG)
#define CCMU_PLL_PERI_PAT1_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_PAT1_CTRL_REG)
#define CCMU_PLL_DDR_PAT0_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_DDR_PAT0_CTRL_REG)
#define CCMU_PLL_DDR_PAT1_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_DDR_PAT1_CTRL_REG)
#define CCMU_PLL_CPU_BIAS_REG	 (SUNXI_CCM_AON_BASE + PLL_CPU_BIAS_REG)
#define CCMU_PLL_PERI_BIAS_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_BIAS_REG)
#define CCMU_PLL_DDR_BIAS_REG	 (SUNXI_CCM_AON_BASE + PLL_DDR_BIAS_REG)
#define CCMU_PLL_CPU_TUN_REG		 (SUNXI_CCM_AON_BASE + PLL_CPU_TUN_REG)
#define CCMU_PLL_FUNC_CFG_REG	 (SUNXI_CCM_AON_BASE + PLL_FUNC_CFG_REG)

#define CCMU_PLL_CPUX_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_CPU_CTRL_REG)
#define CCMU_AON_PLL_CPU_D_1      (0)
#define CCMU_AON_PLL_CPU_D_2      (1)
#define CCMU_AON_PLL_CPU_D_4      (3)
#define CCMU_AON_PLL_CPU_M_1      (0)
#define CCMU_AON_PLL_CPU_M_2      (1)
#define CCMU_AON_PLL_CPU_M_3      (2)
#define CCMU_AON_PLL_CPU_M_4      (3)
#define CCMU_AON_PLL_CPU_M_5      (4)
#define CCMU_AON_PLL_CPU_N_24     (23)
#define CCMU_AON_PLL_CPU_N_25     (24)
#define CCMU_AON_PLL_CPU_N_40     (39)
#define CCMU_AON_PLL_CPU_N_41     (40)
#define CCMU_AON_PLL_CPU_N_50     (49)
#define CCMU_AON_PLL_CPU_N_96     (95)
#define CCMU_AON_PLL_CPU_N_99     (98)
#define CCMU_AON_PLL_CPU_N_118    (117)
#define CCMU_AON_PLL_CPU_N_192    (191)

#define CCMU_PLL_PERI_CTRL0_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL0_REG)
#define CCMU_PLL_PERI_CTRL1_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL1_REG)
#define CCMU_PLL_VIDEO_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_VIDEO_CTRL_REG)
#define CCMU_PLL_CSI_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_CSI_CTRL_REG)

#define CCMU_AHB_CLK_REG	     (SUNXI_CCM_AON_BASE + AHB_CLK_REG)
#define CCMU_APB_CLK_REG	     (SUNXI_CCM_AON_BASE + APB_CLK_REG)
#define CCMU_APB_SPEC_CLK_REG	 (SUNXI_CCM_AON_BASE + APB_SPEC_CLK_REG)

#define CCMU_E90X_CLK_REG	     (SUNXI_CCM_AON_BASE + E907_CLK_REG)
#define CCMU_E90X_CLK_CPU_M_2    (1)

#define CCMU_A27_CLK_REG	     (SUNXI_CCM_AON_BASE + A27L2_CLK_REG)
#define CCMU_A27_CLK_CPU_M_1     (0)
#define CCMU_A27_CLK_CPU_M_2     (1)
#define CCMU_A27_CLK_CPU_M_3     (2)

#define CCMU_HOSC_FREQ_DET_REG   (SUNXI_CCM_AON_BASE + HOSC_FREQ_DET)
#define HOSC_24M_COUNTER         (46875)
#define HOSC_40M_COUNTER         (78125)
#define HOSC_FREQ_24M            (24)
#define HOSC_FREQ_40M            (40)

#define CCMU_FUNC_CFG_REG   (SUNXI_CCM_AON_BASE + PLL_FUNC_CFG_REG)
#endif
