/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __SUN55IW6_PRCM_CCU_H__
#define __SUN55IW6_PRCM_CCU_H__

#define PRCM_CCU_REG_BASE      0x7010000  /* PRCM_BASE */

enum sun55iw6_prcm_ccu_clk_id
{
	CLK_PRCM_AHBS_BUS,
	//CLK_PRCM_APBS0_BUS,
	CLK_PRCM_APBS1_BUS,
	CLK_PRCM_APBS1_DIV,
	CLK_PRCM_R_SPI_FUNC,
	//CLK_PRCM_R_SPI_FUNC_MUX,
	//CLK_PRCM_R_SPI_FUNC_DIV,
	//CLK_PRCM_R_SPI_FUNC_GATE,
	CLK_PRCM_R_SPI_BUS,
	CLK_PRCM_R_UART0_BUS,
	CLK_PRCM_R_UART1_BUS,
};

/* provide some legacy macro to be compatible with legacy code  */
#define CLK_R_UART0 CLK_PRCM_R_UART0_BUS
#define CLK_R_UART1 CLK_PRCM_R_UART1_BUS

#if 0
#define CLK_R_TIMER0		0
#define CLK_R_TIMER1		1
#define CLK_R_TIMER2		2
#define CLK_R_TIMER3		3
#define CLK_R_TIMER		4
#define CLK_R_TWD		5
#define CLK_R_PWM		6
#define CLK_R_BUS_PWM		7
#define CLK_R_SPI		8
#define CLK_R_BUS_SPI		9
#define CLK_R_MBOX		10
#define CLK_R_UART1		11
#define CLK_R_UART0		12
#define CLK_R_TWI1		13
#define CLK_R_TWI0		14
#define CLK_R_PPU		15
#define CLK_R_TZMA		16
#define CLK_R_CPUS_BIST		17
#define CLK_R_IRRX		18
#define CLK_R_BUS_IRRX		19
#define CLK_RTC			20
#define CLK_R_CPUCFG		21
#define CLK_R_AHB 		22
#define CLK_R_APBS0		23
#define CLK_R_APBS1		24

#define CLK_R_NUMBER		(CLK_R_APBS1 + 1)
#endif

enum sun55iw6_prcm_ccu_rst_id
{
	RST_PRCM_RV_MSGBOX_BUS,
	RST_PRCM_R_SPI_BUS,
	RST_PRCM_R_UART0_BUS,
	RST_PRCM_R_UART1_BUS,
};

/* provide some legacy macro to be compatible with legacy code  */
#define RST_BUS_R_UART0 RST_PRCM_R_UART0_BUS
#define RST_BUS_R_UART1 RST_PRCM_R_UART1_BUS

#if 0
#define RST_BUS_R_TIMER		0
#define RST_BUS_R_PWM		1
#define RST_BUS_R_SPI		2
#define RST_BUS_R_MBOX		3
#define RST_BUS_R_UART1		4
#define RST_BUS_R_UART0		5
#define RST_BUS_R_TWI1		6
#define RST_BUS_R_TWI0		7
#define RST_BUS_R_IRRX		8
#define RST_BUS_RTC		9
#define RST_BUS_R_CPUCFG	10

#define RST_R_BUS_NUMBER   (RST_BUS_R_CPUCFG + 1)
#endif

#endif
