/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __SUN55IW6_APP_CCU_H__
#define __SUN55IW6_APP_CCU_H__

#define APP_CCU_REG_BASE      0x02002000

enum sun55iw6_app_ccu_clk_id
{
	CLK_APP_PLL_PERI0,
	CLK_APP_PLL_PERI0_2X_P0_DIV,
	CLK_APP_PLL_PERI0_800M_P1_DIV,
	CLK_APP_PLL_PERI0_480M_P2_DIV,
	CLK_APP_PLL_PERI0_600M_DIV,
	CLK_APP_PLL_PERI0_400M_DIV,
	CLK_APP_PLL_PERI0_300M_DIV,
	CLK_APP_PLL_PERI0_200M_DIV,
	CLK_APP_PLL_PERI0_160M_DIV,
	CLK_APP_PLL_PERI0_150M_DIV,
	CLK_APP_AHB_BUS,
	//CLK_APP_AHB_DIV, //后面可以合并成1个
	CLK_APP_APB_UART_BUS,
	CLK_APP_NSI_BUS,
	CLK_APP_MBUS,
	CLK_APP_RV_MSGBOX_BUS,
	//CLK_PRCM_APBS0_BUS,
	//CLK_PRCM_APBS1_BUS,
	CLK_APP_UART0_BUS,
	CLK_APP_UART1_BUS,
	CLK_APP_UART2_BUS,
	CLK_APP_UART3_BUS,
	CLK_APP_UART4_BUS,
	CLK_APP_UART5_BUS,
	CLK_APP_UART6_BUS,
	CLK_APP_UART7_BUS,
	CLK_APP_UART8_BUS,
	CLK_APP_UART9_BUS,
	CLK_APP_UART10_BUS,
	CLK_APP_UART11_BUS,
	CLK_APP_UART12_BUS,
	CLK_APP_UART13_BUS,
	CLK_APP_UART14_BUS,
	//CLK_PRCM_UART1_BUS,
	APP_CCU_CLK_NUMBER,
};

/* for the id name of legacy clocks */
#define CLK_MSGBOX_RV CLK_APP_RV_MSGBOX_BUS
#define CLK_BUS_UART0 CLK_APP_UART0_BUS
#define CLK_BUS_UART1 CLK_APP_UART1_BUS
#define CLK_BUS_UART2 CLK_APP_UART2_BUS
#define CLK_BUS_UART3 CLK_APP_UART3_BUS
#define CLK_BUS_UART4 CLK_APP_UART4_BUS
#define CLK_BUS_UART5 CLK_APP_UART5_BUS
#define CLK_BUS_UART6 CLK_APP_UART6_BUS
#define CLK_BUS_UART7 CLK_APP_UART7_BUS
#define CLK_BUS_UART8 CLK_APP_UART8_BUS
#define CLK_BUS_UART9 CLK_APP_UART9_BUS
#define CLK_BUS_UART10 CLK_APP_UART10_BUS
#define CLK_BUS_UART11 CLK_APP_UART11_BUS
#define CLK_BUS_UART12 CLK_APP_UART12_BUS
#define CLK_BUS_UART13 CLK_APP_UART13_BUS
#define CLK_BUS_UART14 CLK_APP_UART14_BUS

#if 0
#define CLK_PLL_DDR		0
#define CLK_PLL_PERI0_PARENT	1
#define CLK_PLL_PERI0_2X	2
#define CLK_PERI0_DIV3		3
#define CLK_PLL_PERI0_800M	4
#define CLK_PLL_PERI0_480M	5
#define CLK_PLL_PERI0_600M	6
#define CLK_PLL_PERI0_400M	7
#define CLK_PLL_PERI0_300M	8
#define CLK_PLL_PERI0_200M	9
#define CLK_PLL_PERI0_160M	10
#define CLK_PLL_PERI0_16M	11
#define CLK_PLL_PERI0_150M	12
#define CLK_PLL_PERI0_25M	13
#define CLK_PLL_PERI1_PARENT	14
#define CLK_PLL_PERI1_2X	15
#define CLK_PLL_PERI1_800M	16
#define CLK_PLL_PERI1_480M	17
#define CLK_PLL_PERI1_600M	18
#define CLK_PLL_PERI1_400M	19
#define CLK_PLL_PERI1_300M	20
#define CLK_PLL_PERI1_200M	21
#define CLK_PLL_PERI1_160M	22
#define CLK_PLL_PERI1_150M	23
#define CLK_PLL_VIDEO0_PARENT	24
#define CLK_PLL_VIDEO0_4X	25
#define CLK_PLL_VIDEO0_1X	26
#define CLK_PLL_VIDEO1_PARENT	27
#define CLK_PLL_VIDEO1_4X	28
#define CLK_PLL_VIDEO1_3X	29
#define CLK_PLL_VE		30
#define CLK_PLL_AUDIO0_4X	31
#define CLK_PLL_AUDIO1_4X	32
#define CLK_PLL_NPU_4X		33
#define CLK_AHB			34
#define CLK_APB0		35
#define CLK_APB1		36
#define CLK_APB_UART		37
#define CLK_TRACE		38
#define CLK_GIC			39
#define CLK_ITS0_ACLK		40
#define CLK_ITS0_HCLK		41
#define CLK_NSI			42
#define CLK_NSI_CFG		43
#define CLK_MBUS		44
#define CLK_IOMMU		45
#define CLK_MBUS_GMAC1_GATE	46
#define CLK_MBUS_GMAC0_GATE	47
#define CLK_MBUS_ISP_GATE	48
#define CLK_MBUS_CSI_GATE	49
#define CLK_MBUS_NAND_GATE	50
#define CLK_MBUS_DMA1_GATE	51
#define CLK_MBUS_CE_GATE	52
#define CLK_MBUS_VE_GATE	53
#define CLK_MBUS_DMA0_GATE	54
#define CLK_DMA0		55
#define CLK_DMA1		56
#define CLK_SPINLOCK		57
#define CLK_MSGBOX0		58
#define CLK_MSGBOX_CORE0	59
#define CLK_MSGBOX_CORE1	60
#define CLK_MSGBOX_CORE2	61
#define CLK_MSGBOX_CORE3	62
#define CLK_MSGBOX_RV		63
#define CLK_PWM0		64
#define CLK_PWM1		65
#define CLK_PWM2		66
#define CLK_DBGSYS		67
#define CLK_SYSDAP		68
#define CLK_TIMER0		69
#define CLK_TIMER1		70
#define CLK_TIMER2		71
#define CLK_TIMER3		72
#define CLK_TIMER4		73
#define CLK_TIMER5		74
#define CLK_TIMER6		75
#define CLK_TIMER7		76
#define CLK_BUS_TIMER		77
#define CLK_TIMER0_RV		78
#define CLK_TIMER1_RV		79
#define CLK_TIMER2_RV		80
#define CLK_TIMER3_RV		81
#define CLK_BUS_TIMER_RV	82
#define CLK_DE			83
#define CLK_DE0			84
#define CLK_G2D			85
#define CLK_BUS_G2D		86
#define CLK_VE			87
#define CLK_BUS_VE		88
#define CLK_CE			89
#define CLK_CE_SYS		90
#define CLK_BUS_CE		91
#define CLK_NPU			92
#define CLK_NPU_TZMA		93
#define CLK_BUS_NPU		94
#define CLK_RV_CORE		95
#define CLK_RV_TS		96
#define CLK_RV_CFG		97
#define CLK_DRAM		98
#define CLK_BUS_DRAM		99
#define CLK_NAND0		100
#define CLK_NAND0_CLK2X		101
#define CLK_BUS_NAND0		102
#define CLK_SMHC0		103
#define CLK_BUS_SMHC0		104
#define CLK_SMHC1		105
#define CLK_BUS_SMHC1		106
#define CLK_SMHC2		107
#define CLK_BUS_SMHC2		108
#define CLK_BUS_UART0		109
#define CLK_BUS_UART1		110
#define CLK_BUS_UART2		111
#define CLK_BUS_UART3		112
#define CLK_BUS_UART4		113
#define CLK_BUS_UART5		114
#define CLK_BUS_UART6		115
#define CLK_BUS_UART7		116
#define CLK_BUS_UART8		117
#define CLK_BUS_UART9		118
#define CLK_BUS_UART10		119
#define CLK_BUS_UART11		120
#define CLK_BUS_UART12		121
#define CLK_BUS_UART13		122
#define CLK_BUS_UART14		123
#define CLK_TWI0		124
#define CLK_TWI1		125
#define CLK_TWI2		126
#define CLK_TWI3		127
#define CLK_TWI4		128
#define CLK_TWI5		129
#define CLK_TWI6		130
#define CLK_SPI0		131
#define CLK_BUS_SPI0		132
#define CLK_SPI1		133
#define CLK_BUS_SPI1		134
#define CLK_SPI2		135
#define CLK_BUS_SPI2		136
#define CLK_SPIF		137
#define CLK_BUS_SPIF		138
#define CLK_SPI3		139
#define CLK_BUS_SPI3		140
#define CLK_SPI4		141
#define CLK_BUS_SPI4		142
#define CLK_GPADC0		143
#define CLK_BUS_GPADC0		144
#define CLK_GPADC1		145
#define CLK_BUS_GPADC1		146
#define CLK_GPADC2		147
#define CLK_BUS_GPADC2		148
#define CLK_GPADC3		149
#define CLK_BUS_GPADC3		150
#define CLK_THS			151
#define CLK_IRRX0		152
#define CLK_BUS_IRRX0		153
#define CLK_IRTX		154
#define CLK_BUS_IRTX		155
#define CLK_LRADC		156
#define CLK_TPADC_24M		157
#define CLK_TPADC		158
#define CLK_LBC			159
#define CLK_LBC_NSI_AHB		160
#define CLK_BUS_LBC		161
#define CLK_IRRX1		162
#define CLK_BUS_IRRX1		163
#define CLK_IRRX2		164
#define CLK_BUS_IRRX2		165
#define CLK_IRRX3		166
#define CLK_BUS_IRRX3		167
#define CLK_I2SPCM0		168
#define CLK_BUS_I2SPCM0		169
#define CLK_I2SPCM1		170
#define CLK_BUS_I2SPCM1		171
#define CLK_I2SPCM2		172
#define CLK_BUS_I2SPCM2		173
#define CLK_I2SPCM3		174
#define CLK_BUS_I2SPCM3		175
#define CLK_OWA_TX		176
#define CLK_OWA_RX		177
#define CLK_OWA			178
#define CLK_DMIC		179
#define CLK_BUS_DMIC		180
#define CLK_AUDIO_CODEC_DAC_1X	181
#define CLK_AUDIO_CODEC		182
#define CLK_USB			183
#define CLK_USB20_0_DEVICE	184
#define CLK_USB20_0_HOST_EHCI	185
#define CLK_USB20_0_HOST_OHCI	186
#define CLK_USB1		187
#define CLK_USB20_1_HOST_EHCI	188
#define CLK_USB20_1_HOST_OHCI	189
#define CLK_USB2_REF		190
#define CLK_USB2_SUSPEND	191
#define CLK_USB3_REF		192
#define CLK_USB30		193
#define CLK_PCIE_REF_AUX	194
#define CLK_PCIE_SLV		195
#define CLK_SERDES_PHY_CFG	196
#define CLK_SERDES_PHY_REF	197
#define CLK_SERDES_AXI		198
#define CLK_BUS_SERDES		199
#define CLK_AHB_SERDES		200
#define CLK_GMAC0_PHY		201
#define CLK_GMAC0_PTP		202
#define CLK_GMAC0		203
#define CLK_GMAC1_PHY		204
#define CLK_GMAC1_PTP		205
#define CLK_GMAC1		206
#define CLK_GMAC_NSI		207
#define CLK_VO0_TCONLCD0	208
#define CLK_BUS_VO0_TCONLCD0	209
#define CLK_DSI0		210
#define CLK_BUS_DSI0		211
#define CLK_VO0_COMBPHY0	212
#define CLK_DPSS		213
#define CLK_LEDC		214
#define CLK_BUS_LEDC		215
#define CLK_CSI_MASTER0		216
#define CLK_CSI_MASTER1		217
#define CLK_CSI_MASTER2		218
#define CLK_CSI_MASTER3		219
#define CLK_CSI			220
#define CLK_BUS_CSI		221
#define CLK_ISP			222
#define CLK_USB0_USB1_24M	223
#define CLK_BUS_ISP		224

#define CLK_NUMBER	(CLK_BUS_ISP + 1)
#endif

enum sun55iw6_app_ccu_rst_id
{
	//RST_APP_AHB_BUS,
	//RST_APP_APB_UART_BUS,
	RST_APP_RV_MSGBOX_BUS,
	//RST_PRCM_APBS0_BUS,
	//RST_PRCM_APBS1_BUS,
	RST_APP_UART0_BUS,
	RST_APP_UART1_BUS,
	RST_APP_UART2_BUS,
	RST_APP_UART3_BUS,
	RST_APP_UART4_BUS,
	RST_APP_UART5_BUS,
	RST_APP_UART6_BUS,
	RST_APP_UART7_BUS,
	RST_APP_UART8_BUS,
	RST_APP_UART9_BUS,
	RST_APP_UART10_BUS,
	RST_APP_UART11_BUS,
	RST_APP_UART12_BUS,
	RST_APP_UART13_BUS,
	RST_APP_UART14_BUS,
	//RST_PRCM_UART1_BUS,
};

/* for the id name of legacy resets */
#define RST_BUS_MSGBOX_RV RST_APP_RV_MSGBOX_BUS
#define RST_BUS_UART0 RST_APP_UART0_BUS
#define RST_BUS_UART1 RST_APP_UART1_BUS
#define RST_BUS_UART2 RST_APP_UART2_BUS
#define RST_BUS_UART3 RST_APP_UART3_BUS
#define RST_BUS_UART4 RST_APP_UART4_BUS
#define RST_BUS_UART5 RST_APP_UART5_BUS
#define RST_BUS_UART6 RST_APP_UART6_BUS
#define RST_BUS_UART7 RST_APP_UART7_BUS
#define RST_BUS_UART8 RST_APP_UART8_BUS
#define RST_BUS_UART9 RST_APP_UART9_BUS
#define RST_BUS_UART10 RST_APP_UART10_BUS
#define RST_BUS_UART11 RST_APP_UART11_BUS
#define RST_BUS_UART12 RST_APP_UART12_BUS
#define RST_BUS_UART13 RST_APP_UART13_BUS
#define RST_BUS_UART14 RST_APP_UART14_BUS


#if 0
#define RST_BUS_ITS0		0
#define RST_BUS_NSI		1
#define RST_BUS_NSI_CFG		2
#define RST_BUS_DMA0		3
#define RST_BUS_DMA1		4
#define RST_BUS_SPINLOCK	5
#define RST_BUS_MSGBOX0		6
#define RST_BUS_MSGBOX_CORE0	7
#define RST_BUS_MSGBOX_CORE1	8
#define RST_BUS_MSGBOX_CORE2	9
#define RST_BUS_MSGBOX_CORE3	10
#define RST_BUS_MSGBOX_RV	11
#define RST_BUS_PWM0		12
#define RST_BUS_PWM1		13
#define RST_BUS_PWM2		14
#define RST_BUS_DBGSY		15
#define RST_BUS_SYSDAP		16
#define RST_BUS_TIMER		17
#define RST_BUS_TIMER_RV	18
#define RST_BUS_DE0		19
#define RST_BUS_G2D		20
#define RST_BUS_DE_SY		21
#define RST_BUS_VE		22
#define RST_BUS_CE_SY		23
#define RST_BUS_CE		24
#define RST_BUS_NPU_GLB		25
#define RST_BUS_NPU_AHB		26
#define RST_BUS_NPU_AXI		27
#define RST_BUS_NPU_CORE	28
#define RST_BUS_RV_SY		29
#define RST_BUS_RV_CORE		30
#define RST_BUS_RV_CFG		31
#define RST_BUS_DRAM		32
#define RST_BUS_NAND0		33
#define RST_BUS_SMHC0		34
#define RST_BUS_SMHC1		35
#define RST_BUS_SMHC2		36
#define RST_BUS_UART0		37
#define RST_BUS_UART1		38
#define RST_BUS_UART2		39
#define RST_BUS_UART3		40
#define RST_BUS_UART4		41
#define RST_BUS_UART5		42
#define RST_BUS_UART6		43
#define RST_BUS_UART7		44
#define RST_BUS_UART8		45
#define RST_BUS_UART9		46
#define RST_BUS_UART10		47
#define RST_BUS_UART11		48
#define RST_BUS_UART12		49
#define RST_BUS_UART13		50
#define RST_BUS_UART14		51
#define RST_BUS_TWI0		52
#define RST_BUS_TWI1		53
#define RST_BUS_TWI2		54
#define RST_BUS_TWI3		55
#define RST_BUS_TWI4		56
#define RST_BUS_TWI5		57
#define RST_BUS_TWI6		58
#define RST_BUS_SPI0		59
#define RST_BUS_SPI1		60
#define RST_BUS_SPI2		61
#define RST_BUS_SPIF		62
#define RST_BUS_SPI3		63
#define RST_BUS_SPI4		64
#define RST_BUS_GPADC0		70
#define RST_BUS_GPADC1		71
#define RST_BUS_GPADC2		72
#define RST_BUS_GPADC3		73
#define RST_BUS_TH		74
#define RST_BUS_IRRX0		75
#define RST_BUS_IRTX		76
#define RST_BUS_LRADC		77
#define RST_BUS_TPADC		78
#define RST_BUS_LBC		79
#define RST_BUS_IRRX1		80
#define RST_BUS_IRRX2		81
#define RST_BUS_IRRX3		82
#define RST_BUS_I2SPCM0		83
#define RST_BUS_I2SPCM1		84
#define RST_BUS_I2SPCM2		85
#define RST_BUS_I2SPCM3		86
#define RST_BUS_OWA		87
#define RST_BUS_DMIC		88
#define RST_BUS_AUDIO_CODEC	89
#define RST_USB_PHY0_RSTN	90
#define RST_USB_20_0_DEVICE	91
#define RST_USB_20_0_HOST_EHCI	92
#define RST_USB_20_0_HOST_OHCI	93
#define RST_USB_PHY1_RSTN	94
#define RST_USB_20_1_HOST_EHCI	95
#define RST_USB_20_1_HOST_OHCI	96
#define RST_USB_30		97
#define RST_BUS_PCIE		98
#define RST_BUS_PCIE_PWRUP	99
#define RST_BUS_SERDES_NOPPU	100
#define RST_BUS_SERDE		101
#define RST_BUS_GMAC0_AXI	102
#define RST_BUS_GMAC0		103
#define RST_BUS_GMAC1_AXI	104
#define RST_BUS_GMAC1		105
#define RST_BUS_VO0_TCONLCD0	106
#define RST_BUS_LVDS0		107
#define RST_BUS_DSI0		108
#define RST_BUS_DP		109
#define RST_BUS_VIDEO_OUT0	110
#define RST_BUS_LEDC		111
#define RST_BUS_CSI		112
#define RST_BUS_ISP		113
#define RST_BUS_NPU_TZMA_AHB	114
#define RST_BUS_NPU_TZMA_APB	115

#define RST_BUS_NUMBER 	(RST_BUS_NPU_TZMA_APB + 1)
#endif

#endif  /* __SUN55IW6_APP_CCU_H__ */
