/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __RTC_WDT_SUN300IW1_H__
#define __RTC_WDT_SUN300IW1_H__

#define SUNXI_RTC_WDG_BASE         (0x4A001000)
#define RTC_WDG_IRQ_EN_REG         (SUNXI_RTC_WDG_BASE + 0x0000)
#define RTC_WDG_IRQ_STA_REG        (SUNXI_RTC_WDG_BASE + 0x0004)
#define RTC_WDG_SRST_REG           (SUNXI_RTC_WDG_BASE + 0x0008)
#define RTC_WDG_CTRL_REG           (SUNXI_RTC_WDG_BASE + 0x0010)
#define RTC_WDG_CFG_REG            (SUNXI_RTC_WDG_BASE + 0x0014)
#define RTC_WDG_MODE_REG           (SUNXI_RTC_WDG_BASE + 0x0018)
#define RTC_WDG_OUTPUT_CFG_REG     (SUNXI_RTC_WDG_BASE + 0x001C)
#define RTC_WDG_VERISCV_REG        (SUNXI_RTC_WDG_BASE + 0x0020)

#define RTC_WDG_KEY_FIELD_16AA   (0x16AA << 16)
#define RTC_WDG_KEY_FIELD_0A57   (0x0A57 << 1)
#define RTC_WDG_CLK_SEL_SHIFT         (8U)
#define RTC_WDG_CLK_SEL_VMASK         (0x1U)
#define RTC_WDG_RST_MODE_SHIFT        (0U)
#define RTC_WDG_RST_MODE_VMASK        (0x3U)
#define RTC_WDG_INTERVAL_SHIFT         (4U)
#define RTC_WDG_INTERVAL_VMASK         (0x3FFU)
#define RTC_WDG_EN_SHIFT               (0U)
#define RTC_WDG_EN_VMASK               (0x1U)
#define RTC_WDG_RESTART_SHIFT          (0U)
#define RTC_WDG_RESTART_VMASK          (0x1U)
#define RTC_WDG_SRST_EN_SHIFT          (0U)
#define RTC_WDG_SRST_EN_VMASK          (0x1U)
#define RTC_WDG_IRQ_EN_MASK            (0x00000001)
#define RTC_WDG_IRQ_STA_MASK           (0x00000001)

#define SUNXI_IRQ_RTC_WDG              MAKE_IRQn(184U, 0)

typedef int (*rtc_wdg_callback_t)(void);

typedef enum {
	RTC_WDG_CLK_32000 = 0U,
	RTC_WDG_CLK_32768,
	RTC_WDG_CLK_MAX,
} RTC_WDG_Clk_t;

typedef enum {
	RTC_WDG_MODE_RST_SYS   = 1U,
	RTC_WDG_MODE_INTERRUPT = 2U,
	RTC_WDG_MODE_MAX,
} RTC_WDG_Mode_t;

typedef struct {
	uint32_t period;
	RTC_WDG_Clk_t clksel;
	RTC_WDG_Mode_t mode;
	rtc_wdg_callback_t callback;
}rtc_wdg_cfg_t;
#endif /*__RTC_WDT_SUN300IW1_H__  */

