/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef __KERNEL_TEST_H__
#define __KERNEL_TEST_H__

enum kernel_test_ret_code
{
	KERNEL_TEST_RET_OK = 0,
	KERNEL_TEST_RET_CREATE_THREAD_FAILED = 11,
	KERNEL_TEST_RET_INVALID_OS_TICK_FREQ,
	KERNEL_TEST_RET_NOT_CONTINUOUS_TICK,
	KERNEL_TEST_RET_INVALID_TIMESTAMP_DIFF,
	KERNEL_TEST_RET_IMPRECISE_OS_TICK_FREQ,
	KERNEL_TEST_RET_SCHEDULE_WHEN_INT_DIS,
	KERNEL_TEST_RET_MAX,
	KERNEL_TEST_RET_CREATE_PTHREAD_FAILED,
	KERNEL_TEST_RET_THREAD_JOIN_FAILED,
	KERNEL_TEST_RET_THREAD_JOIN_ABNORMAL,
	KERNEL_TEST_RET_THREAD_CANCEL_FAILED,
	KERNEL_TEST_RET_THREAD_CANCEL_ABNORMAL,
	KERNEL_TEST_RET_THREAD_SETNAME_NP_FAILED,
	KERNEL_TEST_RET_THREAD_SETNAME_NP_ABNORMAL,
	KERNEL_TEST_RET_THREAD_GETNAME_NP_FAILED,
	KERNEL_TEST_RET_PTHREAD_ATTR_INIT_FAILED,
	KERNEL_TEST_RET_PTHREAD_ATTR_GET_STACKSIZE_FAILED,
	KERNEL_TEST_RET_PTHREAD_ATTR_SET_STACKSIZE_FAILED,
	KERNEL_TEST_RET_PTHREAD_ATTR_SET_STACKSIZE_ABNORMAL,
	KERNEL_TEST_RET_PTHREAD_ATTR_DESTORY_FAILED,
	KERNEL_TEST_RET_PTHREAD_BARRIER_ABNORMAL,
	KERNEL_TEST_RET_PTHREAD_BARRIER_INIT_FAILED,
	KERNEL_TEST_RET_PTHREAD_BARRIER_DESTORY_FAILED,
	KERNEL_TEST_RET_PTHREAD_CONF_INIT_FAILED,
	KERNEL_TEST_RET_PTHREAD_COND_SIGNAL_FAILED,
	KERNEL_TEST_RET_PTHREAD_COND_SIGNAL_ABNORMAL,
	KERNEL_TEST_RET_PTHREAD_CONF_DESTROY_FAILED,
	KERNEL_TEST_RET_PTHREAD_MUTEX_LOCK_FAILED,
	KERNEL_TEST_RET_PTHREAD_MUTEX_UNLOCK_FAILED,
	KERNEL_TEST_RET_PTHREAD_MUTEX_INIT_FAILED,
	KERNEL_TEST_RET_PTHREAD_MUTEX_TIMEDLOCK_FAILED,
	KERNEL_TEST_RET_PTHREAD_MUTEX_TRYLOCK_FAILED,
	KERNEL_TEST_RET_PTHREAD_MUTEX_DESTROY_FAILED

};

#define kernel_test_dbg(fmt,...) os_test_dbg("[%s] "fmt, thread_name, ##__VA_ARGS__)
#define kernel_test_info(fmt,...) os_test_info("[%s] "fmt, thread_name, ##__VA_ARGS__)
#define kernel_test_warn(fmt,...) os_test_warn("[%s] "fmt, thread_name, ##__VA_ARGS__)
#define kernel_test_err(fmt,...) os_test_err("[%s] "fmt, thread_name, ##__VA_ARGS__)

int os_tick_test(void);
int os_schedule_test(void);
int os_pthread_test(void);

#endif /* __KERNEL_TEST_H__ */
