/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef __AMP_USER_RESOURCE_H__
#define __AMP_USER_RESOURCE_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Macro For OpenAMP */

#ifdef CONFIG_AMP_USER_RESOURCE_0
#define AMP_USER_RESOURCE_0
#endif

#ifdef CONFIG_AMP_USER_RESOURCE_1
#define AMP_USER_RESOURCE_1
#endif

#ifdef CONFIG_AMP_USER_RESOURCE_2
#define AMP_USER_RESOURCE_2
#endif

#ifdef CONFIG_AMP_USER_RESOURCE_3
#define AMP_USER_RESOURCE_3
#endif

#define LOAD_USER_RSC_FORM_PARTITION (0xff)
#define USER_RSC_TYPE_PARTITION LOAD_USER_RSC_FORM_PARTITION


#define USER_RSC_PARTITION_NAME(id) CONFIG_AMP_USER_RESOURCE_##id##_PARTITION_NAME
#define USER_RSC_DATA_LEN(id) CONFIG_AMP_USER_RESOURCE_##id##_DATA_LEN


#define USER_RSC_DATA_BUF_VAR_DEFINITION(id) \
	__attribute__((section(".amp_user_rsc"))) unsigned char g_user_rsc_data_buf##id[USER_RSC_DATA_LEN(id)]

#define USER_RSC_DATA_BUF_VAR_DECLARATION(id) extern unsigned char g_user_rsc_data_buf##id[]

#define USER_RSC_DATA_BUF_ADDR(id) (void *)&g_user_rsc_data_buf##id


#define USER_RSC_MEMBER_DEFINITION(id) struct fw_rsc_user_resource amp_user_resource##id;
#define USER_RSC_MEMBER_OFFSET(id) offsetof(struct sunxi_resource_table, amp_user_resource##id),

#define USER_RSC_MEMBER_DATA(id, user_rsc_type) \
	.amp_user_resource##id = { \
		.type = RSC_AMP_USER_RESOURCE, \
		.da = (uint32_t)USER_RSC_DATA_BUF_ADDR(id), \
		.len = USER_RSC_DATA_LEN(id), \
		.reserved = 0, \
		.src_type = user_rsc_type, \
		.src_name = USER_RSC_PARTITION_NAME(id), \
	},


#ifdef AMP_USER_RESOURCE_0
USER_RSC_DATA_BUF_VAR_DECLARATION(0);
#define USER_RSC_0_MEMBER_DEFINITION USER_RSC_MEMBER_DEFINITION(0)
#define USER_RSC_0_MEMBER_OFFSET USER_RSC_MEMBER_OFFSET(0)
#define USER_RSC_0_MEMBER_DATA USER_RSC_MEMBER_DATA(0, USER_RSC_TYPE_PARTITION)
#define USER_RSC_0_ENTRIES (1)
#else
#define USER_RSC_0_MEMBER_DEFINITION
#define USER_RSC_0_MEMBER_OFFSET
#define USER_RSC_0_MEMBER_DATA
#define USER_RSC_0_ENTRIES (0)
#endif

#ifdef AMP_USER_RESOURCE_1
USER_RSC_DATA_BUF_VAR_DECLARATION(1);
#define USER_RSC_1_MEMBER_DEFINITION USER_RSC_MEMBER_DEFINITION(1)
#define USER_RSC_1_MEMBER_OFFSET USER_RSC_MEMBER_OFFSET(1)
#define USER_RSC_1_MEMBER_DATA USER_RSC_MEMBER_DATA(1, USER_RSC_TYPE_PARTITION)
#define USER_RSC_1_ENTRIES (1)
#else
#define USER_RSC_1_MEMBER_DEFINITION
#define USER_RSC_1_MEMBER_OFFSET
#define USER_RSC_1_MEMBER_DATA
#define USER_RSC_1_ENTRIES (0)
#endif

#ifdef AMP_USER_RESOURCE_2
USER_RSC_DATA_BUF_VAR_DECLARATION(2);
#define USER_RSC_2_MEMBER_DEFINITION USER_RSC_MEMBER_DEFINITION(2)
#define USER_RSC_2_MEMBER_OFFSET USER_RSC_MEMBER_OFFSET(2)
#define USER_RSC_2_MEMBER_DATA USER_RSC_MEMBER_DATA(2, USER_RSC_TYPE_PARTITION)
#define USER_RSC_2_ENTRIES (1)
#else
#define USER_RSC_2_MEMBER_DEFINITION
#define USER_RSC_2_MEMBER_OFFSET
#define USER_RSC_2_MEMBER_DATA
#define USER_RSC_2_ENTRIES (0)
#endif

#ifdef AMP_USER_RESOURCE_3
USER_RSC_DATA_BUF_VAR_DECLARATION(3);
#define USER_RSC_3_MEMBER_DEFINITION USER_RSC_MEMBER_DEFINITION(3)
#define USER_RSC_3_MEMBER_OFFSET USER_RSC_MEMBER_OFFSET(3)
#define USER_RSC_3_MEMBER_DATA USER_RSC_MEMBER_DATA(3, USER_RSC_TYPE_PARTITION)
#define USER_RSC_3_ENTRIES (1)
#else
#define USER_RSC_3_MEMBER_DEFINITION
#define USER_RSC_3_MEMBER_OFFSET
#define USER_RSC_3_MEMBER_DATA
#define USER_RSC_3_ENTRIES (0)
#endif


#define AMP_USER_RESOURCE_ENTRIES	(USER_RSC_0_ENTRIES + USER_RSC_1_ENTRIES + USER_RSC_2_ENTRIES + USER_RSC_3_ENTRIES)

#define AMP_USER_RESOURCE_MEMBERS_DEFINITION \
	USER_RSC_0_MEMBER_DEFINITION \
	USER_RSC_1_MEMBER_DEFINITION \
	USER_RSC_2_MEMBER_DEFINITION \
	USER_RSC_3_MEMBER_DEFINITION

#define AMP_USER_RESOURCE_MEMBERS_OFFSET \
	USER_RSC_0_MEMBER_OFFSET \
	USER_RSC_1_MEMBER_OFFSET \
	USER_RSC_2_MEMBER_OFFSET \
	USER_RSC_3_MEMBER_OFFSET

#define AMP_USER_RESOURCE_MEMBERS_DATA \
	USER_RSC_0_MEMBER_DATA \
	USER_RSC_1_MEMBER_DATA \
	USER_RSC_2_MEMBER_DATA \
	USER_RSC_3_MEMBER_DATA


/* User API */

typedef struct amp_user_resource
{
	uint32_t id;
	int type;
	const char *part_name;

	uint32_t len;
	unsigned char *buf;
} amp_user_resource_t;

int get_amp_user_resource(uint32_t id, amp_user_resource_t *user_rsc);
void show_user_resource(uint32_t id);
void show_all_user_resource(void);

#ifdef __cplusplus
}
#endif

#endif /* __AMP_USER_RESOURCE_H__ */