# Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
#
# Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
# the people's Republic of China and other countries.
# All Allwinner Technology Co.,Ltd. trademarks are used with permission.
#
# DISCLAIMER
# THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
# IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
# IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
# ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
# ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
# COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
# YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
#
# THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
# PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
# WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
# THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
# OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
# IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#
XRADIO_SRCDIR = $(BUILD_DIR)/components/common/aw/xradio

ifeq ($(CONFIG_ARCH_SUN8IW18P1), y)
PLT_CFLAGS += -I $(BASE)/tools/gcc-arm-melis-eabi-8-2019-q3-update/arm-melis-eabi/include
PLT_CFLAGS += -I $(BASE)/kernel/FreeRTOS/Source/include/
PLT_CFLAGS += -I $(BASE)/kernel/FreeRTOS/Source/port/
PLT_CFLAGS += -I $(BASE)/kernel/FreeRTOS/Source/portable/GCC/ARM_CA9
else ifeq ($(CONFIG_ARCH_SUN20IW2P1), y)
ifeq ($(CONFIG_ARCH_RISCV)_$(CONFIG_ARCH_RISCV_C906), y_y)
PLT_CFLAGS += -I $(BASE)/tools/riscv64-elf-x86_64-20201104/include
PLT_CFLAGS += -I $(BASE)/kernel/FreeRTOS-orig/Source/include/
PLT_CFLAGS += -I $(BASE)/kernel/FreeRTOS-orig/Source/port/
PLT_CFLAGS += -I $(BASE)/kernel/FreeRTOS-orig/Source/portable/GCC/RISC-V/
PLT_CFLAGS += -I $(BASE)/include/arch/riscv/
PLT_CFLAGS += -I $(BASE)/arch/risc-v/
else ifeq ($(CONFIG_ARCH_ARM_CORTEX_M33), y)
PLT_CFLAGS += -I $(BASE)/tools/gcc-arm-none-eabi-8-2019-q3-update/arm-none-eabi/include
PLT_CFLAGS += -I $(BASE)/kernel/FreeRTOS-orig/Source/include/
PLT_CFLAGS += -I $(BASE)/kernel/FreeRTOS-orig/Source/port/
PLT_CFLAGS += -I $(BASE)/kernel/FreeRTOS-orig/Source/portable/GCC/ARM_CM33_NTZ/non_secure/
PLT_CFLAGS += -I $(BASE)/arch/arm/armv8m/include/cmsis/
endif
endif

PLT_CFLAGS += -I $(BASE)/components/common/aw/xradio/include/
