/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __INTERRUPT_NVIC_H
#define __INTERRUPT_NVIC_H

#define NVIC_SET_EN(n)      (NVIC_BASE + 0x000 + (n) * 0x04) /* set enable register 0~15 */
#define NVIC_CLR_EN(n)      (NVIC_BASE + 0x080 + (n) * 0x04) /* clear enable register 0~15 */
#define NVIC_PEND_SET(n)    (NVIC_BASE + 0x100 + (n) * 0x04) /* set pending register 0~15 */
#define NVIC_PEND_CLR(n)    (NVIC_BASE + 0x180 + (n) * 0x04) /* clear pending register 0~15 */
#define NVIC_PEND_ACTIVE(n) (NVIC_BASE + 0x200 + (n) * 0x04) /* active bit register 0~15 */
#define NVIC_PRIORITY(n)    (NVIC_BASE + 0x300 + (n) * 0x04) /* active bit register 0~15 */

#define NVIC_SECUREFAULT	 (7)

#define NVIC_PERIPH_IRQ_OFFSET (16)

typedef enum {
	INT_TG_SEC 		= 0,
	INT_TG_NONSEC 	= 1
} INT_TG_STATE;

void null_exception(void);
void HardFaultHandler(void);
void BusFaultHandler(void);
void SecureFaultHandler(void);
void MemoryFaultHandler(void);
void UsageFaultHandler(void);
#endif
