/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef __INTERRUPT_TEST_H__
#define __INTERRUPT_TEST_H__

#include <hal_interrupt.h>

#if defined(CONFIG_ARCH_ARM_CORTEX_M33)
#define IRQ_BASE_ADDR 0xE000E000
#define ENABLE_BASE 0x100
#define IRQ_NUM 128
#define IRQ_START 0
#define GET_IRQ_STATUS(i) (readl(IRQ_BASE_ADDR + ENABLE_BASE + (i/32) * 4) >> (i % 32) & 1UL)
#elif defined(CONFIG_ARCH_RISCV_C906)
#define IRQ_BASE_ADDR 0x50000000
#define ENABLE_BASE 0x2000
#define IRQ_NUM 140
#define IRQ_START 1
#define GET_IRQ_STATUS(i) (readl(IRQ_BASE_ADDR + ENABLE_BASE + (i/32) * 4) >> (i % 32) & 1UL)
#elif defined(CONFIG_ARCH_RISCV_E906)
#define IRQ_BASE_ADDR 0xE0800000
#define ENABLE_BASE 0x1000
#define IRQ_NUM 256
#define IRQ_START 0
#define GET_IRQ_STATUS(i) ((readl(IRQ_BASE_ADDR + ENABLE_BASE + 4 * i) >> 8) & 0x1UL)
#elif defined(CONFIG_ARCH_RISCV_E907)
#ifdef CONFIG_ARCH_SUN55IW6P1
#define IRQ_BASE_ADDR 0x30800000
#define ENABLE_BASE 0x1000
#define IRQ_NUM 256
#define IRQ_START 16
#define GET_IRQ_STATUS(i) ((readl(IRQ_BASE_ADDR + ENABLE_BASE + 4 * i) >> 8) & 0x1UL)
#elif CONFIG_ARCH_SUN300IW1
#define IRQ_BASE_ADDR 0x30800000
#define ENABLE_BASE 0x1000
#define IRQ_NUM 208
#define IRQ_START 16
#define GET_IRQ_STATUS(i) ((readl(IRQ_BASE_ADDR + ENABLE_BASE + 4 * i) >> 8) & 0x1UL)
#else
#error The platform does not support Interrupt testcase, palse do not set CONFIG_COMPONENTS_OSTEST_OSAL_INTERRUPT.
#endif
#elif defined(CONFIG_ARCH_DSP)
#define IRQ_BASE_ADDR 0x40023400
#define ENABLE_BASE 0x40
#define IRQ_NUM 128
#define IRQ_START 0
#define GET_IRQ_STATUS(i) (readl(IRQ_BASE_ADDR + ENABLE_BASE + (i/32) * 4) >> (i % 32) & 1UL)
#else
#error The platform does not support Interrupt testcase, palse do not set CONFIG_COMPONENTS_OSTEST_OSAL_INTERRUPT.
#endif

enum interrupt_test_ret_code
{
	INTERRUPT_TEST_RET_OK = 0,
    INTERRUPT_TEST_RET_FAILED,
    INTERRUPT_TEST_RET_ENABLE_FAIL,
    INTERRUPT_TEST_RET_DISABLE_FAIL,
    INTERRUPT_TEST_RET_DISABLE_IRQSAVE_FAIL,
    INTERRUPT_TEST_RET_ENABLE_IRQSRORE,
    INTERRUPT_TEST_RET_IRQ_ENABLE_FAIL,
    INTERRUPT_TEST_RET_SET_PENDING_FAIL,
    INTERRUPT_TEST_RET_CLEAN_PENDING_FAIL,

};

int cmd_test_interrupt(int argc, char **argv);

#endif /* __INTERRUPT_TEST_H__ */
