/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __QUEUE_TEST_H__
#define __QUEUE_TEST_H__

#include <hal_time.h>
#include <hal_queue.h>
#include <hal_thread.h>

typedef struct {
	hal_queue_t queue;
	hal_mailbox_t mailbox;
	void *q_thread;
	void *m_thread;
	int q_val;
	int m_val;
	char q_data[64];
	char m_data[64];
	int m_data_send;
	int q_data_send;
	int is_complete1;
	int is_complete2;
} QueueParams;

enum queue_test_ret
{
	QUEUE_TEST_RET_OK = 0,
	QUEUE_TEST_RET_CREATE_THREAD_FAILED = 100,
	QUEUE_TEST_RET_START_THREAD_FAILED,
	QUEUE_TEST_RET_CREATE_QUEUE_FAILED,
	QUEUE_TEST_RET_QUEUE_EMPTY_FAILED,
	QUEUE_TEST_RET_SEND_FAILED,
	QUEUE_TEST_RET_SEND_WAIT_FAILED,
	QUEUE_TEST_RET_RECV_FAILED,
	QUEUE_TEST_RET_RECV_ABNORMAL,
	QUEUE_TEST_RET_QUEUE_DELETE_FAILED
};

enum mailbox_test_ret
{
	MAILBOX_TEST_RET_OK = 0,
	MAILBOX_TEST_RET_CREATE_THREAD_FAILED = 120,
	MAILBOX_TEST_RET_START_THREAD_FAILED,
	MAILBOX_TEST_RET_CREATE_MALIBOX_FAILED,
	MAILBOX_TEST_RET_MAILBOX_EMPTY_FAILED,
	MAILBOX_TEST_RET_SEND_FAILED,
	MAILBOX_TEST_RET_SEND_WAIT_FAILED,
	MAILBOX_TEST_RET_RECV_FAILED,
	MAILBOX_TEST_RET_RECV_ABNORMAL,
	MAILBOX_TEST_RET_MAILBOX_DELETE_FAILED
};

int cmd_osal_queue_test(int argc, char **argv);
int cmd_osal_mailbox_test(int argc, char **argv);

#endif /* __QUEUE_TEST_H__ */

