/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __THREAD_TEST_H__
#define __THREAD_TEST_H__

#include <hal_time.h>
#include <hal_thread.h>

typedef struct {
	int var;
	char data[32];
	void *thread;
	void *thread_self;
	int is_need_exit;
	int is_complete;
} ThreadParams;

enum thread_test_ret
{
	THREAD_TEST_RET_OK = 0,
	THREAD_TEST_RET_THREAD_CREATE_FAILED = 160,
	THREAD_TEST_RET_THREAD_START_FAILED,
	THREAD_TEST_RET_THREAD_START_ABNORMAL,
	THREAD_TEST_RET_THREAD_SELF_FAILED,
	THREAD_TEST_RET_THREAD_SUSPEND_FAILED,
	THREAD_TEST_RET_THREAD_RESUME_FAILED,
	THREAD_TEST_RET_THREAD_SCHEDULER_SUSPEND_FAILED,
	THREAD_TEST_RET_THREAD_SCHEDULER_SUSPEND_ABNORMAL,
	THREAD_TEST_RET_THREAD_SCHEDULER_RESUME_FAILED,
	THREAD_TEST_RET_THREAD_SCHEDULER_IS_RUNNING_FAILED,
	THREAD_TEST_RET_THREAD_IS_IN_CRITICAL_FAILED,
	THREAD_TEST_RET_THREAD_STOP_FAILED,
};

int cmd_osal_thread_test(int argc, char **argv);

#endif /* __THREAD_TEST_H__ */

