/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __UART_SUN55IW3_H__
#define __UART_SUN55IW3_H__

/* config for DSP */
#if defined(CONFIG_ARCH_DSP) || defined(CONFIG_ARCH_RISCV)
#include <interrupt.h>

#define SYS_UART_NUM 7

#define SUNXI_CLK_UART0 CLK_BUS_UART0
#define SUNXI_RST_UART0 RST_BUS_UART0

#define SUNXI_CLK_UART1 CLK_BUS_UART1
#define SUNXI_RST_UART1 RST_BUS_UART1

#define SUNXI_CLK_UART2 CLK_UART2
#define SUNXI_RST_UART2 RST_BUS_UART2

#define SUNXI_CLK_UART3 CLK_UART3
#define SUNXI_RST_UART3 RST_BUS_UART3

#define SUNXI_CLK_UART4 CLK_UART4
#define SUNXI_RST_UART4 RST_BUS_UART4

#define SUNXI_CLK_UART5 CLK_UART5
#define SUNXI_RST_UART5 RST_BUS_UART5

#define SUNXI_CLK_UART6 CLK_UART6
#define SUNXI_RST_UART6 RST_BUS_UART6

#define SUNXI_CLK_UART7 CLK_UART7
#define SUNXI_RST_UART7 RST_BUS_UART7

#define SUNXI_CLK_UART8 CLK_BUS_R_UART0
#define SUNXI_RST_UART8 RST_R_UART0

#define SUNXI_CLK_UART9 CLK_BUS_R_UART1
#define SUNXI_RST_UART9 RST_R_UART1

#ifdef CONFIG_ARCH_RISCV
#include <hal_interrupt.h>
#define SUNXI_IRQ_UART0		MAKE_IRQn(90, 3)
#define SUNXI_IRQ_UART1		MAKE_IRQn(90, 4)
#define SUNXI_IRQ_UART2		MAKE_IRQn(90, 5)
#define SUNXI_IRQ_UART3		MAKE_IRQn(90, 6)
#define SUNXI_IRQ_UART4		MAKE_IRQn(90, 7)
#define SUNXI_IRQ_UART5		MAKE_IRQn(90, 8)
#define SUNXI_IRQ_UART6		MAKE_IRQn(91, 1)
#define SUNXI_IRQ_UART7		MAKE_IRQn(91, 2)
#define SUNXI_IRQ_UART8		MAKE_IRQn(66, 0)
#define SUNXI_IRQ_UART9		MAKE_IRQn(67, 0)
#else
#define SUNXI_IRQ_UART0		MAKE_IRQn(38, 2)|RINTC_IRQ_MASK
#define SUNXI_IRQ_UART1		MAKE_IRQn(38, 3)|RINTC_IRQ_MASK
#define SUNXI_IRQ_UART2		MAKE_IRQn(38, 4)|RINTC_IRQ_MASK
#define SUNXI_IRQ_UART3		MAKE_IRQn(38, 5)|RINTC_IRQ_MASK
#define SUNXI_IRQ_UART4		MAKE_IRQn(38, 6)|RINTC_IRQ_MASK
#define SUNXI_IRQ_UART5		MAKE_IRQn(38, 7)|RINTC_IRQ_MASK
#define SUNXI_IRQ_UART6		MAKE_IRQn(39, 0)|RINTC_IRQ_MASK
#define SUNXI_IRQ_UART7		MAKE_IRQn(39, 1)|RINTC_IRQ_MASK
#define SUNXI_IRQ_UART8		(RINTC_IRQ_MASK | 67)
#define SUNXI_IRQ_UART9		30
#endif

#define SUNXI_UART0_BASE	(0x02500000)
#define SUNXI_UART1_BASE	(0x02500400)
#define SUNXI_UART2_BASE	(0x02500800)
#define SUNXI_UART3_BASE	(0x02500c00)
#define SUNXI_UART4_BASE	(0x02501000)
#define SUNXI_UART5_BASE	(0x02501400)
#define SUNXI_UART6_BASE	(0x02501800)
#define SUNXI_UART7_BASE	(0x02501c00)
#define SUNXI_UART8_BASE	(0x07080000)
#define SUNXI_UART9_BASE	(0x07080400)

#define UART_FIFO_SIZE		(64)

#define UART0_GPIO_FUNCTION	(2)
#define UART1_GPIO_FUNCTION	(2)
#define UART2_GPIO_FUNCTION	(2)
#define UART3_GPIO_FUNCTION	(2)
#define UART4_GPIO_FUNCTION	(2)
#define UART5_GPIO_FUNCTION	(2)
#define UART6_GPIO_FUNCTION	(2)
#define UART7_GPIO_FUNCTION	(2)
#define UART8_GPIO_FUNCTION	(2)
#define UART9_GPIO_FUNCTION	(2)

#define UART0_TX		GPIOB(9)
#define UART0_RX		GPIOB(10)
#define UART1_TX		GPIOG(6)
#define UART1_RX		GPIOG(7)
#define UART2_TX		GPIOB(0)
#define UART2_RX		GPIOB(1)
#define UART3_TX		GPIOH(4)
#define UART3_RX		GPIOH(5)
#define UART4_TX		GPIOD(18)
#define UART4_RX		GPIOD(19)
#define UART5_TX		GPIOE(11)
#define UART5_RX		GPIOE(12)
#define UART6_TX		GPIOK(18)
#define UART6_RX		GPIOK(19)
#define UART7_TX		GPIOB(11)
#define UART7_RX		GPIOB(12)
#define UART8_TX		GPIOL(2)
#define UART8_RX		GPIOL(3)
#define UART9_TX		GPIOM(0)
#define UART9_RX		GPIOM(1)

#endif

#endif /*__UART_SUN55IW3_H__  */
