/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __UART_SUN55IW6_H__
#define __UART_SUN55IW6_H__

/* config for DSP */

#if defined(CONFIG_ARCH_RISCV) || defined(CONFIG_ARCH_ARM)
#include <interrupt.h>
#include <hal_interrupt.h>

#define SYS_UART_NUM 14

#define SUNXI_CLK_UART0 CLK_BUS_UART0
#define SUNXI_RST_UART0 RST_BUS_UART0

#define SUNXI_CLK_UART1 CLK_BUS_UART1
#define SUNXI_RST_UART1 RST_BUS_UART1

#define SUNXI_CLK_UART2 CLK_BUS_UART2
#define SUNXI_RST_UART2 RST_BUS_UART2

#define SUNXI_CLK_UART3 CLK_BUS_UART3
#define SUNXI_RST_UART3 RST_BUS_UART3

#define SUNXI_CLK_UART4 CLK_BUS_UART4
#define SUNXI_RST_UART4 RST_BUS_UART4

#define SUNXI_CLK_UART5 CLK_BUS_UART5
#define SUNXI_RST_UART5 RST_BUS_UART5

#define SUNXI_CLK_UART6 CLK_BUS_UART6
#define SUNXI_RST_UART6 RST_BUS_UART6

#define SUNXI_CLK_UART7 CLK_BUS_UART7
#define SUNXI_RST_UART7 RST_BUS_UART7

#define SUNXI_CLK_UART8 CLK_BUS_UART8
#define SUNXI_RST_UART8 RST_BUS_UART8

#define SUNXI_CLK_UART9 CLK_BUS_UART9
#define SUNXI_RST_UART9 RST_BUS_UART9

#define SUNXI_CLK_UART10 CLK_BUS_UART10
#define SUNXI_RST_UART10 RST_BUS_UART10

#define SUNXI_CLK_UART11 CLK_BUS_UART11
#define SUNXI_RST_UART11 RST_BUS_UART11

#define SUNXI_CLK_UART12 CLK_BUS_UART12
#define SUNXI_RST_UART12 RST_BUS_UART12

#define SUNXI_CLK_UART13 CLK_BUS_UART13
#define SUNXI_RST_UART13 RST_BUS_UART13

#define SUNXI_CLK_UART14 CLK_BUS_UART14
#define SUNXI_RST_UART14 RST_BUS_UART14

#define SUNXI_CLK_UART15 CLK_R_UART0
#define SUNXI_RST_UART15 RST_BUS_R_UART0

#define SUNXI_CLK_UART16 CLK_R_UART1
#define SUNXI_RST_UART16 RST_BUS_R_UART1

#if defined(CONFIG_ARCH_ARM_CORTEX_A55)
#define SUNXI_IRQ_UART0		(34)
#define SUNXI_IRQ_UART1		(35)
#define SUNXI_IRQ_UART2		(36)
#define SUNXI_IRQ_UART3		(37)
#define SUNXI_IRQ_UART4		(38)
#define SUNXI_IRQ_UART5		(39)
#define SUNXI_IRQ_UART6		(40)
#define SUNXI_IRQ_UART7		(41)
#define SUNXI_IRQ_UART8		(180)
#define SUNXI_IRQ_UART9		(181)
#define SUNXI_IRQ_UART10	(182)
#define SUNXI_IRQ_UART11	(183)
#define SUNXI_IRQ_UART12	(184)
#define SUNXI_IRQ_UART13	(185)
#define SUNXI_IRQ_UART14	(186)
#define SUNXI_IRQ_UART15	(237)
#define SUNXI_IRQ_UART16	(238)
#else
#define SUNXI_IRQ_UART0		MAKE_IRQn(18, 0)
#define SUNXI_IRQ_UART1		MAKE_IRQn(19, 0)
#define SUNXI_IRQ_UART2		MAKE_IRQn(20, 0)
#define SUNXI_IRQ_UART3		MAKE_IRQn(21, 0)
#define SUNXI_IRQ_UART4		MAKE_IRQn(22, 0)
#define SUNXI_IRQ_UART5		MAKE_IRQn(23, 0)
#define SUNXI_IRQ_UART6		MAKE_IRQn(24, 0)
#define SUNXI_IRQ_UART7		MAKE_IRQn(25, 0)
#define SUNXI_IRQ_UART8		MAKE_IRQn(164, 0)
#define SUNXI_IRQ_UART9		MAKE_IRQn(165, 0)
#define SUNXI_IRQ_UART10	MAKE_IRQn(166, 0)
#define SUNXI_IRQ_UART11	MAKE_IRQn(167, 0)
#define SUNXI_IRQ_UART12	MAKE_IRQn(168, 0)
#define SUNXI_IRQ_UART13	MAKE_IRQn(169, 0)
#define SUNXI_IRQ_UART14	MAKE_IRQn(170, 0)
#define SUNXI_IRQ_UART15	MAKE_IRQn(221, 0)
#define SUNXI_IRQ_UART16	MAKE_IRQn(222, 0)
#endif
#define SUNXI_UART0_BASE	(0x02600000)
#define SUNXI_UART1_BASE	(0x02601000)
#define SUNXI_UART2_BASE	(0x02602000)
#define SUNXI_UART3_BASE	(0x02603000)
#define SUNXI_UART4_BASE	(0x02604000)
#define SUNXI_UART5_BASE	(0x02605000)
#define SUNXI_UART6_BASE	(0x02606000)
#define SUNXI_UART7_BASE	(0x02607000)
#define SUNXI_UART8_BASE	(0x02608000)
#define SUNXI_UART9_BASE	(0x02609000)
#define SUNXI_UART10_BASE	(0x0260A000)
#define SUNXI_UART11_BASE	(0x0260B000)
#define SUNXI_UART12_BASE	(0x0260C000)
#define SUNXI_UART13_BASE	(0x0260D000)
#define SUNXI_UART14_BASE	(0x0260E000)
#define SUNXI_UART15_BASE	(0x07080000)
#define SUNXI_UART16_BASE	(0x07081000)

#define UART_FIFO_SIZE		(64)

#define UART0_GPIO_FUNCTION	(2)
#define UART1_GPIO_FUNCTION	(2)
#define UART2_GPIO_FUNCTION	(2)
#define UART3_GPIO_FUNCTION	(6)
#define UART4_GPIO_FUNCTION	(2)
#define UART5_GPIO_FUNCTION	(3)
#define UART6_GPIO_FUNCTION	(5)
#define UART7_GPIO_FUNCTION	(3)
#define UART8_GPIO_FUNCTION	(7)
#define UART9_GPIO_FUNCTION	(7)
#define UART10_GPIO_FUNCTION	(7)
#define UART11_GPIO_FUNCTION	(4)
#define UART12_GPIO_FUNCTION	(4)
#define UART13_GPIO_FUNCTION	(4)
#define UART14_GPIO_FUNCTION	(3)
#define UART15_GPIO_FUNCTION	(2)
#define UART16_GPIO_FUNCTION	(3)


#define UART0_TX		GPIOB(9)
#define UART0_RX		GPIOB(10)
#define UART1_TX		GPIOG(6)
#define UART1_RX		GPIOG(7)
#define UART2_TX		GPIOB(0)
#define UART2_RX		GPIOB(1)
#define UART3_TX		GPIOD(14)
#define UART3_RX		GPIOD(15)
#define UART4_TX		GPIOI(13)
#define UART4_RX		GPIOI(14)
#define UART5_TX		GPIOE(13)
#define UART5_RX		GPIOE(12)
#define UART6_TX		GPIOK(18)
#define UART6_RX		GPIOK(19)
#define UART7_TX		GPIOB(13)
#define UART7_RX		GPIOB(14)
#define UART8_TX		GPIOB(4)
#define UART8_RX		GPIOB(5)
#define UART9_TX		GPIOD(0)
#define UART9_RX		GPIOD(1)
#define UART10_TX		GPIOD(4)
#define UART10_RX		GPIOD(5)
#define UART11_TX		GPIOK(0)
#define UART11_RX		GPIOK(1)
#define UART12_TX		GPIOK(4)
#define UART12_RX		GPIOK(5)
#define UART13_TX		GPIOJ(26)
#define UART13_RX		GPIOJ(27)
#define UART14_TX		GPIOJ(20)
#define UART14_RX		GPIOJ(21)

#define UART15_TX		GPIOL(2)
#define UART15_RX		GPIOL(3)
#define UART16_TX		GPIOM(0)
#define UART16_RX		GPIOM(1)


#define DRQDST_UART15_TX	DRQDST_R_UART0
#define DRQSRC_UART15_RX	DRQSRC_R_UART0

#define DRQDST_UART16_TX	DRQDST_R_UART1
#define DRQSRC_UART16_RX	DRQSRC_R_UART1

#endif

#endif /*__UART_SUN55IW6_H__  */
