/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __UART_SUN300IW1_H__
#define __UART_SUN300IW1_H__

#if defined(CONFIG_ARCH_RISCV)
#include <interrupt.h>
#include <hal_interrupt.h>

#define SYS_UART_NUM 4
#define UART_SCLK CLK_APB_SPC

#define SUNXI_CLK_UART0 CLK_UART0
#define SUNXI_RST_UART0 RST_BUS_UART0

#define SUNXI_CLK_UART1 CLK_UART1
#define SUNXI_RST_UART1 RST_BUS_UART1

#define SUNXI_CLK_UART2 CLK_UART2
#define SUNXI_RST_UART2 RST_BUS_UART2

#define SUNXI_CLK_UART3 CLK_UART3
#define SUNXI_RST_UART3 RST_BUS_UART3

#define SUNXI_IRQ_UART0		MAKE_IRQn(18, 0)
#define SUNXI_IRQ_UART1		MAKE_IRQn(19, 0)
#define SUNXI_IRQ_UART2		MAKE_IRQn(20, 0)
#define SUNXI_IRQ_UART3		MAKE_IRQn(21, 0)

#define SUNXI_UART0_BASE	(0x42500000)
#define SUNXI_UART1_BASE	(0x42500400)
#define SUNXI_UART2_BASE	(0x42500800)
#define SUNXI_UART3_BASE	(0x42500C00)

#if defined(CONFIG_PROJECT_V821_E907_AIGLASS)
#define UART_FIFO_SIZE		(4096)
#else
#define UART_FIFO_SIZE		(64)
#endif

#define UART0_GPIO_FUNCTION	(3)
#define UART1_GPIO_FUNCTION	(6)
#define UART2_GPIO_FUNCTION	(4)
#define UART3_GPIO_FUNCTION	(5)

#define UART0_TX		GPIOC(2)
#define UART0_RX		GPIOC(4)
#define UART1_TX		GPIOD(9)
#define UART1_RX		GPIOD(10)
#define UART2_TX		GPIOC(4)
#define UART2_RX		GPIOC(5)
#define UART3_TX		GPIOA(5)
#define UART3_RX		GPIOA(6)

#endif

#endif /*__UART_SUN300IW1_H__  */
