/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
* Copyright (c) 2024-2030 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __IRQNEST_TEST_H__
#define __IRQNEST_TEST_H__

#include <hal_interrupt.h>
#include <inttypes.h>

#define TEST_NUM_MAX	(HAL_IRQ_PRIO_MAX)
#define INVALID_IRQNUM	(-32)

#ifdef CONFIG_IRQNEST_TEST_CTX_CONTENT_DEBUG
#define irqnest_test_dbg(fmt, arg...)	do { os_test_info(fmt, ##arg); } while (0)
#else
#define irqnest_test_dbg(fmt, arg...)	do { } while (0)
#endif /* IRQNEST_DEBUG_LOG */


/* fpu regs */
#ifdef CONFIG_IRQNEST_FPU_TEST
#define MAX_FPU_GENERAL_REG_NUM		(32)
#define FPU_GENERAL_REG_CNT		(CONFIG_IRQNEST_FPU_GENERAL_REG_CNT)
#define FPU_GENERAL_REG_SIZE		(CONFIG_IRQNEST_FPU_GENERAL_REG_SIZE)

#if (FPU_GENERAL_REG_SIZE != 4) && (FPU_GENERAL_REG_SIZE != 8)
#error Unsupported FPU general register size!
#endif
#if (FPU_GENERAL_REG_SIZE == 4)
typedef uint32_t fpu_reg_t;
typedef float arch_float_t;
#define FPU_REG_TYPE_FMT_STR "08x"
#endif
#if (FPU_GENERAL_REG_SIZE == 8)
typedef uint64_t fpu_reg_t;
typedef double arch_float_t;
#define FPU_REG_TYPE_FMT_STR PRIu64
#endif


void irqnest_fill_fpu_reg_data(uint32_t fpu_reg_cnt, fpu_reg_t *reg_buf, uint32_t integer_part);
void irqnest_dump_fpu_reg_data(int hw_irqid, uint32_t fpu_reg_cnt, const fpu_reg_t *reg_buf);
int irqnest_check_fpu_reg_data(int hw_irqid, uint32_t fpu_reg_cnt, const fpu_reg_t *before, const fpu_reg_t *after, uint32_t integer_part);
#endif /* CONFIG_IRQNEST_FPU_TEST */

/* general and control regs */
#ifdef CONFIG_IRQNEST_OSTEST_GENERAL_CTX_CMP
#define GENERAL_REG_CNT			(CONFIG_IRQNEST_GENERAL_REG_CNT)
#define GENERAL_REG_SIZE		(CONFIG_IRQNEST_GENERAL_REG_SIZE)

#if (GENERAL_REG_SIZE != 4) && (GENERAL_REG_SIZE != 8)
#error Unsupported general register size!
#endif
#if (GENERAL_REG_SIZE == 4)
typedef uint32_t general_reg_t;
#define GENERAL_REG_TYPE_FMT_STR "08x"
#endif
#if (GENERAL_REG_SIZE == 8)
typedef uint64_t general_reg_t;
#define GENERAL_REG_TYPE_FMT_STR PRIu64
#endif

void irqnest_ctx_track_irq_init(void);
#endif /* CONFIG_IRQNEST_OSTEST_GENERAL_CTX_CMP */

int irqnest_platform_get_irq_num(int hw_irqid);
int irqnest_platform_irq_request_config(int hw_irqid);
int irqnest_platform_trigger_irq(int hw_irqid);
void irqnest_platform_clean_pending(int hw_irqid);
#endif /* __IRQNEST_TEST_H__ */
