/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.

 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.

 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY¡¯S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS¡¯SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY¡¯S TECHNOLOGY.


 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.

 */
#ifndef __WUPIO_SUN300IW1_H__
#define __WUPIO_SUN300IW1_H__

#define WUP_IO_EN_REG             (0x4a000050)
#define WUP_IO_DEB_CLK_REG        (0x4a000054)
#define WUP_IO_STA_REG            (0x4a000058)
#define WUP_IO_HOLD_REG           (0x4a00005C)
#define WUP_IO_WUP_GEN_REG        (0x4a000060)
#define WUP_IO_WUP_CYC0_REG       (0x4a000064)
#define WUP_IO_WUP_CYC1_REG       (0x4a000068)

#define WUP_IO_DEB_CLK_SET1_SHIFT (28)
#define WUP_IO_DEB_CLK_SET1_MASK  (0xF << WUP_IO_DEB_CLK_SET1_SHIFT)
#define WUP_IO_DEB_CLK_SET0_SHIFT (24)
#define WUP_IO_DEB_CLK_SET0_MASK  (0xF << WUP_IO_DEB_CLK_SET0_SHIFT)
#define WUP_IO_MODE_SHIFT         (16)
#define WUP_IO_DEB_CLK_SEL_SHIFT  (0)
#define WUP_IO_DEB_CYC_OFFSET     (4)
#define WUP_IO_DEB_CYC_SHIFT      (0)
#define WUP_IO_DEB_CYC_VMASK      (0xF)
#define WUP_IO_HOLD_SHIFT         (0)
#define WUP_IO_EN_SHIFT           (0)
#define WUP_IO_GEN_MASK           (0x00000001)

#define SUXNI_IRQ_WUPIO           MAKE_IRQn(186U, 0)
#define WUP_IO_NUN                (8)
#define WUP_IO_MASK               (0x000000FF)

#endif /* __WUPIO_SUN300IW1_H__ */

