/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY¡¯S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS¡¯SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY¡¯S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __SPI_H
#define __SPI_H

#include "platform.h"
#include "spinand_common.h"

#define CCMU_BASE_ADDR (SUNXI_CCMU_APP_BASE)
#define SPI_BASE_ADDR (SUNXI_SPI0_BASE)
#define SPI_GPIO_BASE_ADDR (SUNXI_SPI0_GPIO_BASE)
#define SPI_CLOCK_SOURCE_FREQUENCY (307000000)

#define SPI_TX_WL		(32)
#define SPI_RX_WL		(32)
#define SPI_FIFO_SIZE	(64)

#define SPI_VAR		(SPI_BASE_ADDR + 0x00)
#define SPI_GCR		(SPI_BASE_ADDR + 0x04)
#define SPI_TCR		(SPI_BASE_ADDR + 0x08)
#define SPI_IER		(SPI_BASE_ADDR + 0x10)
#define SPI_ISR		(SPI_BASE_ADDR + 0x14)
#define SPI_FCR		(SPI_BASE_ADDR + 0x18)
#define SPI_FSR		(SPI_BASE_ADDR + 0x1c)
#define SPI_WCR		(SPI_BASE_ADDR + 0x20)
#define SPI_CCR		(SPI_BASE_ADDR + 0x24)
#define SPI_SDC		(SPI_BASE_ADDR + 0x28)
#define SPI_MBC		(SPI_BASE_ADDR + 0x30)
#define SPI_MTC		(SPI_BASE_ADDR + 0x34)
#define SPI_BCC		(SPI_BASE_ADDR + 0x38)
#define SPI_TXD		(SPI_BASE_ADDR + 0x200)
#define SPI_RXD		(SPI_BASE_ADDR + 0x300)

/* bit field of registers */
#define SPI_SOFT_RST	(1U << 31)
#define SPI_TXPAUSE_EN	(1U << 7)
#define SPI_MASTER		(1U << 1)
#define SPI_ENABLE		(1U << 0)

#define SPI_EXCHANGE	(1U << 31)
#define SPI_SAMPLE_MODE	(1U << 13)
#define SPI_LSB_MODE	(1U << 12)
#define SPI_SAMPLE_CTRL	(1U << 11)
#define SPI_RAPIDS_MODE	(1U << 10)
#define SPI_DUMMY_1		(1U << 9)
#define SPI_DHB			(1U << 8)
#define SPI_SET_SS_1	(1U << 7)
#define SPI_SS_MANUAL	(1U << 6)
#define SPI_SEL_SS0		(0U << 4)
#define SPI_SEL_SS1		(1U << 4)
#define SPI_SEL_SS2		(2U << 4)
#define SPI_SEL_SS3		(3U << 4)
#define SPI_SS_N_INBST	(1U << 3)
#define SPI_SS_ACTIVE0	(1U << 2)
#define SPI_MODE0		(0U << 0)
#define SPI_MODE1		(1U << 0)
#define SPI_MODE2		(2U << 0)
#define SPI_MODE3		(3U << 0)

#define SPI_CPHA        (1U << 0)

#define SPI_SS_INT		(1U << 13)
#define SPI_TC_INT		(1U << 12)
#define SPI_TXUR_INT	(1U << 11)
#define SPI_TXOF_INT	(1U << 10)
#define SPI_RXUR_INT	(1U << 9)
#define SPI_RXOF_INT	(1U << 8)
#define SPI_TXFULL_INT	(1U << 6)
#define SPI_TXEMPT_INT	(1U << 5)
#define SPI_TXREQ_INT	(1U << 4)
#define SPI_RXFULL_INT	(1U << 2)
#define SPI_RXEMPT_INT	(1U << 1)
#define SPI_RXREQ_INT	(1U << 0)
#define SPI_ERROR_INT	(SPI_TXUR_INT|SPI_TXOF_INT|SPI_RXUR_INT|SPI_RXOF_INT)

#define SPI_TXFIFO_RST	(1U << 31)
#define SPI_TXFIFO_TST	(1U << 30)
#define SPI_TXDMAREQ_EN	(1U << 24)
#define SPI_RXFIFO_RST	(1U << 15)
#define SPI_RXFIFO_TST	(1U << 14)
#define SPI_RXDMAREQ_EN	(1U << 8)

#define SPI_MASTER_DUAL	(1U << 28)

/* sample delay mode */
#define SPI_SAMP_MODE_EN	(1U << 2)
#define SPI_SAMP_DL_SW_EN	(1U << 7)
#define DELAY_NORMAL_SAMPLE	(0x100)
#define DELAY_0_5_CYCLE_SAMPLE	(0x000)
#define DELAY_1_CYCLE_SAMPLE	(0x010)
#define DELAY_1_5_CYCLE_SAMPLE	(0x110)
#define DELAY_2_CYCLE_SAMPLE	(0x101)
#define DELAY_2_5_CYCLE_SAMPLE	(0x001)
#define DELAY_3_CYCLE_SAMPLE	(0x011)

void spi_sel_ss(u32 spi_no, u32 ssx);
void spi_config_dual_mode(u32 spi_no, u32 rxdual, u32 dbc, u32 stc);
s32 spi_init(u32 spi_no);
s32 spi_deinit(u32 spi_no);
s32 spi_set_clk(u32 index, u32 clock);
s32 spi_rw(u32 spi_no, u32 tcnt, u8 *txbuf, u32 rcnt, u8 *rxbuf, u32 dummy_cnt);
void spi_sample_point_delay_set_legacy(u32 freq);

#endif
