/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#include "platform_sun55iw6.h"
#include "platform_irq.h"
#include "../irq_core.h"
#include <hal_interrupt.h>

#define REMOTEPROC_E907_READY_TO_STOP	(0x16aa0001)
#define REMOTEPROC_E907_STOP_REC_REG	(0x07090114)

#define CLINT_CPU_MS_INT_IRQ_ID			(3)
#define CLINT_CPU_MT_INT_IRQ_ID			(7)
#define VECTOR11_IRQ_ID				(11)

#define DMAC1_ECC_IRQ_ID			(16)
#define VECTOR17_IRQ_ID				(17)

#define UART0_7_x_IRQ_ID(_port)			(18 + (_port))
#define UART0_IRQ_ID				(UART0_7_x_IRQ_ID(0))
#define UART1_IRQ_ID				(UART0_7_x_IRQ_ID(1))
#define UART2_IRQ_ID				(UART0_7_x_IRQ_ID(2))
#define UART3_IRQ_ID				(UART0_7_x_IRQ_ID(3))
#define UART4_IRQ_ID				(UART0_7_x_IRQ_ID(4))
#define UART5_IRQ_ID				(UART0_7_x_IRQ_ID(5))
#define UART6_IRQ_ID				(UART0_7_x_IRQ_ID(6))
#define UART7_IRQ_ID				(UART0_7_x_IRQ_ID(7))

#define TWI0_5_x_IRQ_ID(_port)			(26 + (_port))
#define TWI0_IRQ_ID				(TWI0_5_x_IRQ_ID(0))
#define TWI1_IRQ_ID				(TWI0_5_x_IRQ_ID(1))
#define TWI2_IRQ_ID				(TWI0_5_x_IRQ_ID(2))
#define TWI3_IRQ_ID				(TWI0_5_x_IRQ_ID(3))
#define TWI4_IRQ_ID				(TWI0_5_x_IRQ_ID(4))
#define TWI5_IRQ_ID				(TWI0_5_x_IRQ_ID(5))

#define SPI0_IRQ_ID				(32)
#define SPI1_IRQ_ID				(33)
#define SPI2_IRQ_ID				(34)

#define PWM0_IRQ_ID				(35)
#define SPI_FLASH_IRQ_ID			(36)

#define SPI3_IRQ_ID				(37)
#define SPI4_IRQ_ID				(38)

#define OWA_IRQ_ID				(39)
#define DMIC_IRQ_ID				(40)
#define AUDIO_CODEC_IRQ_ID			(41)

#define IRTX_IRQ_ID				(42)
#define IRRX0_IRQ_ID				(43)
#define LEDC_IRQ_ID				(44)
#define USB0_DEVICE_IRQ_ID			(45)
#define USB0_EHCI_IRQ_ID			(46)
#define USB0_OHCI_IRQ_ID			(47)
#define USB1_EHCI_IRQ_ID			(48)
#define USB1_OHCI_IRQ_ID			(49)
#define USB2_IRQ_ID				(50)

#define VECTOR51_IRQ_ID				(51)
#define VECTOR52_IRQ_ID				(52)
#define VECTOR53_IRQ_ID				(53)
#define NDFC_IRQ_ID				(54)
#define THS0_IRQ_ID				(55)

#define SMHCx_IRQ_ID(_port)			(56 + (_port))
#define SMHC0_IRQ_ID				(SMHCx_IRQ_ID(0))
#define SMHC1_IRQ_ID				(SMHCx_IRQ_ID(1))
#define SMHC2_IRQ_ID				(SMHCx_IRQ_ID(2))

#define NSI_IRQ_ID				(59)
#define SMC_IRQ_ID				(60)
#define PWM2_IRQ_ID				(61)

#define GMACx_TOP_IRQ_ID(_port)			(62 + (_port))
#define GMAC0_TOP_IRQ_ID			(GMACx_TOP_IRQ_ID(0))
#define GMAC1_TOP_IRQ_ID			(GMACx_TOP_IRQ_ID(1))

#define LBC_IRQ_ID				(64)
#define AHB_HREADY_TIME_OUT_IRQ_ID		(65)
#define DMAC0_CPUX_NS_IRQ_ID			(66)
#define DMAC0_CPUX_S_IRQ_ID			(67)
#define CE_NS_IRQ_ID				(68)
#define CE_S_IRQ_ID				(69)
#define SPINLOCK_IRQ_ID				(70)

#define TIMER_CPUX0_5_x_IRQ_ID(_port)		(71 + (_port))
#define TIMER_CPUX0_IRQ_ID			(TIMER_CPUX0_5_x_IRQ_ID(0))
#define TIMER_CPUX1_IRQ_ID			(TIMER_CPUX0_5_x_IRQ_ID(1))
#define TIMER_CPUX2_IRQ_ID			(TIMER_CPUX0_5_x_IRQ_ID(2))
#define TIMER_CPUX3_IRQ_ID			(TIMER_CPUX0_5_x_IRQ_ID(3))
#define TIMER_CPUX4_IRQ_ID			(TIMER_CPUX0_5_x_IRQ_ID(4))
#define TIMER_CPUX5_IRQ_ID			(TIMER_CPUX0_5_x_IRQ_ID(5))

#define GPADC0_IRQ_ID				(77)
#define GPADC2_IRQ_ID				(78)
#define WDT_CPUX_IRQ_ID				(79)
#define GPADC1_IRQ_ID				(80)
#define IOMMU_IRQ_ID				(81)
#define LRADC_IRQ_ID				(82)

#define GPIOA_NS_IRQ_ID				(83)
#define GPIOA_S_IRQ_ID				(84)
#define GPIOB_NS_IRQ_ID				(85)
#define GPIOB_S_IRQ_ID				(86)
#define GPIOC_NS_IRQ_ID				(87)
#define GPIOC_S_IRQ_ID				(88)
#define GPIOD_NS_IRQ_ID				(89)
#define GPIOD_S_IRQ_ID				(90)
#define GPIOE_NS_IRQ_ID				(91)
#define GPIOE_S_IRQ_ID				(92)
#define GPIOF_NS_IRQ_ID				(93)
#define GPIOF_S_IRQ_ID				(94)
#define GPIOG_NS_IRQ_ID				(95)
#define GPIOG_S_IRQ_ID				(96)
#define GPIOH_NS_IRQ_ID				(97)
#define GPIOH_S_IRQ_ID				(98)
#define GPIOI_NS_IRQ_ID				(99)
#define GPIOI_S_IRQ_ID				(100)
#define GPIOJ_NS_IRQ_ID				(101)
#define GPIOJ_S_IRQ_ID				(102)

#define DE0_IRQ_ID				(103)
#define DE0_CRC_IRQ_ID				(104)
#define VECTOR105_IRQ_ID			(105)
#define TCON_LCD0_IRQ_ID			(106)
#define DSI_IRQ_ID			(107)

#define GMACx_PWR_CLK_CTRL_IRQ_ID(_port)	(108 + (_port) * 3)
#define GMACx_PERCH_TX_IRQ_ID(_port)		(109 + (_port) * 3)
#define GMACx_PERCH_RX_IRQ_ID(_port)		(110 + (_port) * 3)
#define GMAC0_PWR_CLK_CTRL_IRQ_ID		(GMACx_PWR_CLK_CTRL_IRQ_ID(0))
#define GMAC0_PERCH_TX_IRQ_ID			(GMACx_PERCH_TX_IRQ_ID(0))
#define GMAC0_PERCH_RX_IRQ_ID			(GMACx_PERCH_RX_IRQ_ID(0))
#define GMAC1_PWR_CLK_CTRL_IRQ_ID		(GMACx_PWR_CLK_CTRL_IRQ_ID(1))
#define GMAC1_PERCH_TX_IRQ_ID			(GMACx_PERCH_TX_IRQ_ID(1))
#define GMAC1_PERCH_RX_IRQ_ID			(GMACx_PERCH_RX_IRQ_ID(1))

#define PCIE0_EDMAn_IRQ_ID(_ch)			(114 + (_ch))
#define PCIE0_EDMA0_IRQ_ID			(PCIE0_EDMAn_IRQ_ID(0))
#define PCIE0_EDMA1_IRQ_ID			(PCIE0_EDMAn_IRQ_ID(1))
#define PCIE0_EDMA2_IRQ_ID			(PCIE0_EDMAn_IRQ_ID(2))
#define PCIE0_EDMA3_IRQ_ID			(PCIE0_EDMAn_IRQ_ID(3))
#define PCIE0_EDMA4_IRQ_ID			(PCIE0_EDMAn_IRQ_ID(4))
#define PCIE0_EDMA5_IRQ_ID			(PCIE0_EDMAn_IRQ_ID(5))
#define PCIE0_EDMA6_IRQ_ID			(PCIE0_EDMAn_IRQ_ID(6))
#define PCIE0_EDMA7_IRQ_ID			(PCIE0_EDMAn_IRQ_ID(7))
#define PCIE0_SII_IRQ_ID			(122)
#define PCIE0_MSI_IRQ_ID			(123)

#define VECTOR124_IRQ_ID			(124)
#define VECTOR125_IRQ_ID			(125)
#define VECTOR126_IRQ_ID			(126)
#define VECTOR127_IRQ_ID			(127)
#define VECTOR128_IRQ_ID			(128)
#define VECTOR129_IRQ_ID			(129)

#define NPU_SRAM_TZMA_IRQ_ID			(130)
#define VECTOR131_IRQ_ID			(131)
#define NPU_IRQ_ID				(132)
#define IRRX1_IRQ_ID				(133)
#define IRRX2_IRQ_ID				(134)
#define IRRX3_IRQ_ID				(135)
#define VE0_IRQ_ID				(136)
#define DRAMC_DFS_IRQ_ID			(137)

#define CSI_DMAn_IRQ_ID(_ch)			(138 + (_ch))
#define CSI_DMA0_IRQ_ID				(CSI_DMAn_IRQ_ID(0))
#define CSI_DMA1_IRQ_ID				(CSI_DMAn_IRQ_ID(1))
#define CSI_DMA2_IRQ_ID				(CSI_DMAn_IRQ_ID(2))
#define CSI_DMA3_IRQ_ID				(CSI_DMAn_IRQ_ID(3))

#define CSI_VIPPn_IRQ_ID(_ch)			(142 + (_ch))
#define CSI_VIPP0_IRQ_ID			(CSI_VIPPn_IRQ_ID(0))
#define CSI_VIPP1_IRQ_ID			(CSI_VIPPn_IRQ_ID(1))
#define CSI_VIPP2_IRQ_ID			(CSI_VIPPn_IRQ_ID(2))
#define CSI_VIPP3_IRQ_ID			(CSI_VIPPn_IRQ_ID(3))

#define CSI_PARSERn_IRQ_ID(_ch)			(146 + (_ch))
#define CSI_PARSER0_IRQ_ID			(CSI_PARSERn_IRQ_ID(0))
#define CSI_PARSER1_IRQ_ID			(CSI_PARSERn_IRQ_ID(1))
#define CSI_PARSER2_IRQ_ID			(CSI_PARSERn_IRQ_ID(2))

#define CSI_ISPn_IRQ_ID(_ch)			(149 + (_ch))
#define CSI_ISP0_IRQ_ID				(CSI_ISPn_IRQ_ID(0))
#define CSI_ISP1_IRQ_ID				(CSI_ISPn_IRQ_ID(1))
#define CSI_ISP2_IRQ_ID				(CSI_ISPn_IRQ_ID(2))
#define CSI_ISP3_IRQ_ID				(CSI_ISPn_IRQ_ID(3))

#define CSI_CMB_IRQ_ID				(153)
#define CSI_TDM_IRQ_ID				(154)
#define CSI_TOP_PKT_IRQ_ID			(155)

#define GPIOK_NS_IRQ_ID				(156)
#define GPIOK_S_IRQ_ID				(157)

#define PWM1_IRQ_ID				(158)
#define G2D_IRQ_ID				(159)

#define VECTOR160_IRQ_ID			(160)
#define VECTOR161_IRQ_ID			(161)
#define VECTOR162_IRQ_ID			(162)

#define CSI_PARSER3_IRQ_ID			(163)

#define UART8_14_x_IRQ_ID(_port)		(164 + (_port) - 8)
#define UART8_IRQ_ID				(UART8_14_x_IRQ_ID(8))
#define UART9_IRQ_ID				(UART8_14_x_IRQ_ID(9))
#define UART10_IRQ_ID				(UART8_14_x_IRQ_ID(10))
#define UART11_IRQ_ID				(UART8_14_x_IRQ_ID(11))
#define UART12_IRQ_ID				(UART8_14_x_IRQ_ID(12))
#define UART13_IRQ_ID				(UART8_14_x_IRQ_ID(13))
#define UART14_IRQ_ID				(UART8_14_x_IRQ_ID(14))

#define TWI6_IRQ_ID				(171)

#define TIMER_CPUX6_7_x_IRQ_ID(_port)		(172 + (_port) - 6)
#define TIMER_CPUX6_IRQ_ID			(TIMER_CPUX6_7_x_IRQ_ID(6))
#define TIMER_CPUX7_IRQ_ID			(TIMER_CPUX6_7_x_IRQ_ID(7))

#define GPADC3_IRQ_ID				(174)
#define TPADC_IRQ_ID				(175)

#define I2Sx_IRQ_ID(_port)			(176 + (_port))
#define I2S0_IRQ_ID				(I2Sx_IRQ_ID(0))
#define I2S1_IRQ_ID				(I2Sx_IRQ_ID(1))
#define I2S2_IRQ_ID				(I2Sx_IRQ_ID(2))
#define I2S3_IRQ_ID				(I2Sx_IRQ_ID(3))

#define DMAC1_CPUX_NS_IRQ_ID			(180)
#define DMAC1_CPUX_S_IRQ_ID			(181)

#define COREx_MSGBOX_R_IRQ_ID(_to)		(182 + (_to))
#define CORE0_MSGBOX_R_IRQ_ID			(COREx_MSGBOX_R_IRQ_ID(0))
#define CORE1_MSGBOX_R_IRQ_ID			(COREx_MSGBOX_R_IRQ_ID(1))
#define CORE2_MSGBOX_R_IRQ_ID			(COREx_MSGBOX_R_IRQ_ID(2))
#define CORE3_MSGBOX_R_IRQ_ID			(COREx_MSGBOX_R_IRQ_ID(3))

#define CORE0_MSGBOX_CORE1_W_IRQ_ID		(186)
#define CORE0_MSGBOX_CORE2_W_IRQ_ID		(187)
#define CORE0_MSGBOX_CORE3_W_IRQ_ID		(188)

#define CORE1_MSGBOX_CORE0_W_IRQ_ID		(189)
#define CORE1_MSGBOX_CORE2_W_IRQ_ID		(190)
#define CORE1_MSGBOX_CORE3_W_IRQ_ID		(191)

#define CORE2_MSGBOX_CORE0_W_IRQ_ID		(192)
#define CORE2_MSGBOX_CORE1_W_IRQ_ID		(193)
#define CORE2_MSGBOX_CORE3_W_IRQ_ID		(194)

#define CORE3_MSGBOX_CORE0_W_IRQ_ID		(195)
#define CORE3_MSGBOX_CORE1_W_IRQ_ID		(196)
#define CORE3_MSGBOX_CORE2_W_IRQ_ID		(197)

#define NSI_SBR_IRQ_ID				(198)
#define DMAC0_ECC_IRQ_ID			(199)
#define MCU_MSGBOX_R_IRQ_ID			(200)
#define WDT_MCU_IRQ_ID				(201)

#define TIMER_MCUx_IRQ_ID(_port)		(202 + (_port))
#define TIMER_MCU0_IRQ_ID			(TIMER_MCUx_IRQ_ID(0))
#define TIMER_MCU1_IRQ_ID			(TIMER_MCUx_IRQ_ID(1))
#define TIMER_MCU2_IRQ_ID			(TIMER_MCUx_IRQ_ID(2))
#define TIMER_MCU3_IRQ_ID			(TIMER_MCUx_IRQ_ID(3))

#define E907_ECC_IRQ_ID				(206)
#define VECTOR207_IRQ_ID			(207)
#define NMI_IRQ_ID				(208)
#define R_PPU_IRQ_ID				(209)
#define R_TWD_IRQ_ID				(210)
#define WDT_CPUS_IRQ_ID				(211)

#define TIMER_CPUSx_IRQ_ID(_port)		(212 + (_port))
#define TIMER_CPUS0_IRQ_ID			(TIMER_CPUSx_IRQ_ID(0))
#define TIMER_CPUS1_IRQ_ID			(TIMER_CPUSx_IRQ_ID(1))
#define TIMER_CPUS2_IRQ_ID			(TIMER_CPUSx_IRQ_ID(2))
#define TIMER_CPUS3_IRQ_ID			(TIMER_CPUSx_IRQ_ID(3))

#define R_ALARM0_IRQ_ID				(216)

#define GPIOL_NS_IRQ_ID				(217)
#define GPIOL_S_IRQ_ID				(218)
#define GPIOM_NS_IRQ_ID				(219)
#define GPIOM_S_IRQ_ID				(220)

#define R_UARTx_IRQ_ID(_port)			(221 + (_port))
#define R_UART0_IRQ_ID				(R_UARTx_IRQ_ID(0))
#define R_UART1_IRQ_ID				(R_UARTx_IRQ_ID(1))

#define R_TWIx_IRQ_ID(_port)			(223 + (_port))
#define R_TWI0_IRQ_ID				(R_TWIx_IRQ_ID(0))
#define R_TWI1_IRQ_ID				(R_TWIx_IRQ_ID(1))
#define R_TWI2_IRQ_ID				(R_TWIx_IRQ_ID(2))

#define R_IRRX_IRQ_ID				(226)
#define R_PWM_IRQ_ID				(227)
#define SRAM_A2_TZMA_IRQ_ID			(228)
#define R_AHB_HREADY_TIME_OUT_IRQ_ID		(229)
#define R_SPI_IRQ_ID				(230)
#define CPUS_MSGBOX_CPUX_W_IRQ_ID		(231)
#define CPUIDLE_IRQ_ID				(232)
#define VECTOR233_IRQ_ID			(233)
#define SRAM_ECC_IRQ_ID				(234)
#define VECTOR235_IRQ_ID			(235)
#define VECTOR236_IRQ_ID			(236)
#define VECTOR237_IRQ_ID			(237)
#define VECTOR238_IRQ_ID			(238)
#define VECTOR239_IRQ_ID			(239)
#define CPUX_MSGBOX_MCU_W_IRQ_ID		(240)

#define DMAC_IRQ1_NS_IRQ_ID			(241)
#define DMAC_IRQ1_S_IRQ_ID			(242)
#define DMAC1_IRQ1_NS_IRQ_ID			(243)
#define DMAC1_IRQ1_S_IRQ_ID			(244)

#define CPUS_MSGBOX_IRQ_MCU_IRQ_ID		(245)

#define GMAC0_ECC_IRQ_ID			(246)
#define GMAC1_ECC_IRQ_ID			(247)

#define SID_CRC_IRQ_ID				(248)

#define SMHC0_ECC_IRQ_ID			(249)
#define SMHC2_ECC_IRQ_ID			(250)

#define DRAMC_ECC_ERR_IRQ_ID			(251)
#define DRAMC_ECC_ERR_FAULT_IRQ_ID		(252)
#define DRAMC_ECC_AP_ERR_IRQ_ID			(253)
#define DRAMC_ECC_AP_ERR_FAULT_IRQ_ID		(254)

#define DRAMC_SRAM_ECC_IRQ_ID			(255)

#define _CONTACT(__str_a, __str_b)		__str_a##__str_b
#define CONTACT(_str_a, _str_b)			_CONTACT(_str_a, _str_b)

#define _STR(__str)				#__str
#define STR(_str)				_STR(_str)

#define IRQ_STR(_name)				[CONTACT(_name, _IRQ_ID)] = STR(_name)
#define ANON_IRQ_STR(_id)			[CONTACT(CONTACT(VECTOR, _id), _IRQ_ID)] = " "

#define RESERVED_IRQ_STR(_start, _end)		[_start ... _end] = "RESERVED"

const char *irq_major_string[PLAT_CLIC_IRQ_CNT] =
{
	RESERVED_IRQ_STR(0, 2),
	IRQ_STR(CLINT_CPU_MS_INT),
	RESERVED_IRQ_STR(4, 6),
	IRQ_STR(CLINT_CPU_MT_INT),
	RESERVED_IRQ_STR(8, 10),
	ANON_IRQ_STR(11),
	RESERVED_IRQ_STR(12, 15),
	IRQ_STR(DMAC1_ECC),
	ANON_IRQ_STR(17),
	IRQ_STR(UART0),
	IRQ_STR(UART1),
	IRQ_STR(UART2),
	IRQ_STR(UART3),
	IRQ_STR(UART4),
	IRQ_STR(UART5),
	IRQ_STR(UART6),
	IRQ_STR(UART7),
	IRQ_STR(TWI0),
	IRQ_STR(TWI1),
	IRQ_STR(TWI2),
	IRQ_STR(TWI3),
	IRQ_STR(TWI4),
	IRQ_STR(TWI5),
	IRQ_STR(SPI0),
	IRQ_STR(SPI1),
	IRQ_STR(SPI2),
	IRQ_STR(SPI2),
	IRQ_STR(PWM0),
	IRQ_STR(SPI_FLASH),
	IRQ_STR(SPI3),
	IRQ_STR(SPI4),
	IRQ_STR(OWA),
	IRQ_STR(DMIC),
	IRQ_STR(AUDIO_CODEC),
	IRQ_STR(IRTX),
	IRQ_STR(IRRX0),
	IRQ_STR(LEDC),
	IRQ_STR(USB0_DEVICE),
	IRQ_STR(USB0_EHCI),
	IRQ_STR(USB0_OHCI),
	IRQ_STR(USB1_EHCI),
	IRQ_STR(USB1_OHCI),
	IRQ_STR(USB2),
	ANON_IRQ_STR(51),
	ANON_IRQ_STR(52),
	ANON_IRQ_STR(53),
	IRQ_STR(NDFC),
	IRQ_STR(THS0),
	IRQ_STR(SMHC0),
	IRQ_STR(SMHC1),
	IRQ_STR(SMHC2),
	IRQ_STR(NSI),
	IRQ_STR(SMC),
	IRQ_STR(PWM2),
	IRQ_STR(GMAC0_TOP),
	IRQ_STR(GMAC1_TOP),
	IRQ_STR(LBC),
	IRQ_STR(AHB_HREADY_TIME_OUT),
	IRQ_STR(DMAC0_CPUX_NS),
	IRQ_STR(DMAC0_CPUX_S),
	IRQ_STR(CE_NS),
	IRQ_STR(CE_S),
	IRQ_STR(SPINLOCK),
	IRQ_STR(TIMER_CPUX0),
	IRQ_STR(TIMER_CPUX1),
	IRQ_STR(TIMER_CPUX2),
	IRQ_STR(TIMER_CPUX3),
	IRQ_STR(TIMER_CPUX4),
	IRQ_STR(TIMER_CPUX5),
	IRQ_STR(GPADC0),
	IRQ_STR(GPADC2),
	IRQ_STR(WDT_CPUX),
	IRQ_STR(GPADC1),
	IRQ_STR(IOMMU),
	IRQ_STR(LRADC),
	IRQ_STR(GPIOA_NS),
	IRQ_STR(GPIOA_S),
	IRQ_STR(GPIOB_NS),
	IRQ_STR(GPIOB_S),
	IRQ_STR(GPIOC_NS),
	IRQ_STR(GPIOC_S),
	IRQ_STR(GPIOD_NS),
	IRQ_STR(GPIOD_S),
	IRQ_STR(GPIOE_NS),
	IRQ_STR(GPIOE_S),
	IRQ_STR(GPIOF_NS),
	IRQ_STR(GPIOF_S),
	IRQ_STR(GPIOG_NS),
	IRQ_STR(GPIOG_S),
	IRQ_STR(GPIOH_NS),
	IRQ_STR(GPIOH_S),
	IRQ_STR(GPIOI_NS),
	IRQ_STR(GPIOI_S),
	IRQ_STR(GPIOJ_NS),
	IRQ_STR(GPIOJ_S),
	IRQ_STR(DE0),
	IRQ_STR(DE0_CRC),
	ANON_IRQ_STR(105),
	IRQ_STR(TCON_LCD0),
	IRQ_STR(DSI),
	IRQ_STR(GMAC0_PWR_CLK_CTRL),
	IRQ_STR(GMAC0_PERCH_TX),
	IRQ_STR(GMAC0_PERCH_RX),
	IRQ_STR(GMAC1_PWR_CLK_CTRL),
	IRQ_STR(GMAC1_PERCH_TX),
	IRQ_STR(GMAC1_PERCH_RX),
	IRQ_STR(PCIE0_EDMA0),
	IRQ_STR(PCIE0_EDMA1),
	IRQ_STR(PCIE0_EDMA2),
	IRQ_STR(PCIE0_EDMA3),
	IRQ_STR(PCIE0_EDMA4),
	IRQ_STR(PCIE0_EDMA5),
	IRQ_STR(PCIE0_EDMA6),
	IRQ_STR(PCIE0_EDMA7),
	IRQ_STR(PCIE0_SII),
	IRQ_STR(PCIE0_MSI),
	ANON_IRQ_STR(124),
	ANON_IRQ_STR(125),
	ANON_IRQ_STR(126),
	ANON_IRQ_STR(127),
	ANON_IRQ_STR(128),
	ANON_IRQ_STR(129),
	IRQ_STR(NPU_SRAM_TZMA),
	ANON_IRQ_STR(131),
	IRQ_STR(NPU),
	IRQ_STR(IRRX1),
	IRQ_STR(IRRX2),
	IRQ_STR(IRRX3),
	IRQ_STR(VE0),
	IRQ_STR(DRAMC_DFS),
	IRQ_STR(CSI_DMA0),
	IRQ_STR(CSI_DMA1),
	IRQ_STR(CSI_DMA2),
	IRQ_STR(CSI_DMA3),
	IRQ_STR(CSI_VIPP0),
	IRQ_STR(CSI_VIPP1),
	IRQ_STR(CSI_VIPP2),
	IRQ_STR(CSI_VIPP3),
	IRQ_STR(CSI_PARSER0),
	IRQ_STR(CSI_PARSER1),
	IRQ_STR(CSI_PARSER2),
	IRQ_STR(CSI_ISP0),
	IRQ_STR(CSI_ISP1),
	IRQ_STR(CSI_ISP2),
	IRQ_STR(CSI_ISP3),
	IRQ_STR(CSI_CMB),
	IRQ_STR(CSI_TDM),
	IRQ_STR(CSI_TOP_PKT),
	IRQ_STR(GPIOK_NS),
	IRQ_STR(GPIOK_S),
	IRQ_STR(PWM1),
	IRQ_STR(G2D),
	ANON_IRQ_STR(160),
	ANON_IRQ_STR(161),
	ANON_IRQ_STR(162),
	IRQ_STR(CSI_PARSER3),
	IRQ_STR(UART8),
	IRQ_STR(UART9),
	IRQ_STR(UART10),
	IRQ_STR(UART11),
	IRQ_STR(UART12),
	IRQ_STR(UART13),
	IRQ_STR(UART14),
	IRQ_STR(TWI6),
	IRQ_STR(TIMER_CPUX6),
	IRQ_STR(TIMER_CPUX7),
	IRQ_STR(GPADC3),
	IRQ_STR(TPADC),
	IRQ_STR(I2S0),
	IRQ_STR(I2S1),
	IRQ_STR(I2S2),
	IRQ_STR(I2S3),
	IRQ_STR(DMAC1_CPUX_NS),
	IRQ_STR(DMAC1_CPUX_S),
	IRQ_STR(CORE0_MSGBOX_R),
	IRQ_STR(CORE1_MSGBOX_R),
	IRQ_STR(CORE2_MSGBOX_R),
	IRQ_STR(CORE3_MSGBOX_R),
	IRQ_STR(CORE0_MSGBOX_CORE1_W),
	IRQ_STR(CORE0_MSGBOX_CORE2_W),
	IRQ_STR(CORE0_MSGBOX_CORE3_W),
	IRQ_STR(CORE1_MSGBOX_CORE0_W),
	IRQ_STR(CORE1_MSGBOX_CORE2_W),
	IRQ_STR(CORE1_MSGBOX_CORE3_W),
	IRQ_STR(CORE2_MSGBOX_CORE0_W),
	IRQ_STR(CORE2_MSGBOX_CORE1_W),
	IRQ_STR(CORE2_MSGBOX_CORE3_W),
	IRQ_STR(CORE3_MSGBOX_CORE0_W),
	IRQ_STR(CORE3_MSGBOX_CORE1_W),
	IRQ_STR(CORE3_MSGBOX_CORE2_W),
	IRQ_STR(NSI_SBR),
	IRQ_STR(DMAC0_ECC),
	IRQ_STR(MCU_MSGBOX_R),
	IRQ_STR(WDT_MCU),
	IRQ_STR(TIMER_MCU0),
	IRQ_STR(TIMER_MCU1),
	IRQ_STR(TIMER_MCU2),
	IRQ_STR(TIMER_MCU3),
	IRQ_STR(E907_ECC),
	ANON_IRQ_STR(207),
	IRQ_STR(NMI),
	IRQ_STR(R_PPU),
	IRQ_STR(R_TWD),
	IRQ_STR(WDT_CPUS),
	IRQ_STR(TIMER_CPUS0),
	IRQ_STR(TIMER_CPUS1),
	IRQ_STR(TIMER_CPUS2),
	IRQ_STR(TIMER_CPUS3),
	IRQ_STR(R_ALARM0),
	IRQ_STR(GPIOL_NS),
	IRQ_STR(GPIOL_S),
	IRQ_STR(GPIOM_NS),
	IRQ_STR(GPIOM_S),
	IRQ_STR(R_UART0),
	IRQ_STR(R_UART1),
	IRQ_STR(R_TWI0),
	IRQ_STR(R_TWI1),
	IRQ_STR(R_TWI2),
	IRQ_STR(R_IRRX),
	IRQ_STR(R_PWM),
	IRQ_STR(SRAM_A2_TZMA),
	IRQ_STR(R_AHB_HREADY_TIME_OUT),
	IRQ_STR(R_SPI),
	IRQ_STR(CPUS_MSGBOX_CPUX_W),
	IRQ_STR(CPUIDLE),
	ANON_IRQ_STR(233),
	IRQ_STR(SRAM_ECC),
	ANON_IRQ_STR(235),
	ANON_IRQ_STR(236),
	ANON_IRQ_STR(237),
	ANON_IRQ_STR(238),
	ANON_IRQ_STR(239),
	IRQ_STR(CPUX_MSGBOX_MCU_W),
	IRQ_STR(DMAC_IRQ1_NS),
	IRQ_STR(DMAC_IRQ1_S),
	IRQ_STR(DMAC1_IRQ1_NS),
	IRQ_STR(DMAC1_IRQ1_S),
	IRQ_STR(CPUS_MSGBOX_IRQ_MCU),
	IRQ_STR(GMAC0_ECC),
	IRQ_STR(GMAC1_ECC),
	IRQ_STR(SID_CRC),
	IRQ_STR(SMHC0_ECC),
	IRQ_STR(SMHC2_ECC),
	IRQ_STR(DRAMC_ECC_ERR),
	IRQ_STR(DRAMC_ECC_ERR_FAULT),
	IRQ_STR(DRAMC_ECC_AP_ERR),
	IRQ_STR(DRAMC_ECC_AP_ERR_FAULT),
	IRQ_STR(DRAMC_SRAM_ECC),
};

void platform_remoteproc_stop_eve(void)
{
	hal_interrupt_disable();
	irq_core_disable_root_ic_irq();
	hal_writel(REMOTEPROC_E907_READY_TO_STOP, REMOTEPROC_E907_STOP_REC_REG);
	while (1) {
		__asm__ volatile("wfi":::"memory", "cc");
	}
}
