obj-$(CONFIG_COMPONENTS_AW) += aw/
obj-$(CONFIG_COMPONENTS_AW) += common/aw/
obj-$(CONFIG_COMPONENTS_THIRDPARTY) += thirdparty/
obj-$(CONFIG_COMPONENTS_THIRDPARTY) += common/thirdparty/

subdir-ccflags-y += -I components/common/aw/pm/include/
subdir-ccflags-y += -I $(BASE)/kernel/Interface_remap/include/