/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef __AMP_USER_MEMORY_H__
#define __AMP_USER_MEMORY_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Macro For OpenAMP */

#ifdef CONFIG_AMP_USER_MEMORY_0
#define AMP_USER_MEMORY_0
#endif

#ifdef CONFIG_AMP_USER_MEMORY_1
#define AMP_USER_MEMORY_1
#endif

#ifdef CONFIG_AMP_USER_MEMORY_2
#define AMP_USER_MEMORY_2
#endif

#ifdef CONFIG_AMP_USER_MEMORY_3
#define AMP_USER_MEMORY_3
#endif

#define USER_MEM_NAME(id) CONFIG_AMP_USER_MEMORY_DT_NODE_NAME_PREFIX#id

#define GET_USER_MEM_MEMBER_VAR(user_mem_id) \
	if (id == user_mem_id) \
	{ \
		return &resource_table.amp_user_memory##user_mem_id; \
	}

#define USER_MEM_MEMBER_DEFINITION(id) struct fw_rsc_carveout amp_user_memory##id;
#define USER_MEM_MEMBER_OFFSET(id) offsetof(struct sunxi_resource_table, amp_user_memory##id),

#define USER_MEM_MEMBER_DATA(id) \
	.amp_user_memory##id = { \
		.type = RSC_CARVEOUT, \
		.da = -1, \
		.pa = -1, \
		.len = 0, \
		.flags = MEM_NONCACHEABLE, \
		.reserved = 0, \
		.name = USER_MEM_NAME(id), \
	},


#ifdef AMP_USER_MEMORY_0
#define GET_USER_MEM_0_MEMBER_VAR GET_USER_MEM_MEMBER_VAR(0)
#define USER_MEM_0_MEMBER_DEFINITION USER_MEM_MEMBER_DEFINITION(0)
#define USER_MEM_0_MEMBER_OFFSET USER_MEM_MEMBER_OFFSET(0)
#define USER_MEM_0_MEMBER_DATA USER_MEM_MEMBER_DATA(0)
#define USER_MEM_0_ENTRIES (1)
#else
#define GET_USER_MEM_0_MEMBER_VAR
#define USER_MEM_0_MEMBER_DEFINITION
#define USER_MEM_0_MEMBER_OFFSET
#define USER_MEM_0_MEMBER_DATA
#define USER_MEM_0_ENTRIES (0)
#endif

#ifdef AMP_USER_MEMORY_1
#define GET_USER_MEM_1_MEMBER_VAR GET_USER_MEM_MEMBER_VAR(1)
#define USER_MEM_1_MEMBER_DEFINITION USER_MEM_MEMBER_DEFINITION(1)
#define USER_MEM_1_MEMBER_OFFSET USER_MEM_MEMBER_OFFSET(1)
#define USER_MEM_1_MEMBER_DATA USER_MEM_MEMBER_DATA(1)
#define USER_MEM_1_ENTRIES (1)
#else
#define GET_USER_MEM_1_MEMBER_VAR
#define USER_MEM_1_MEMBER_DEFINITION
#define USER_MEM_1_MEMBER_OFFSET
#define USER_MEM_1_MEMBER_DATA
#define USER_MEM_1_ENTRIES (0)
#endif

#ifdef AMP_USER_MEMORY_2
#define GET_USER_MEM_2_MEMBER_VAR GET_USER_MEM_MEMBER_VAR(2)
#define USER_MEM_2_MEMBER_DEFINITION USER_MEM_MEMBER_DEFINITION(2)
#define USER_MEM_2_MEMBER_OFFSET USER_MEM_MEMBER_OFFSET(2)
#define USER_MEM_2_MEMBER_DATA USER_MEM_MEMBER_DATA(2)
#define USER_MEM_2_ENTRIES (1)
#else
#define GET_USER_MEM_2_MEMBER_VAR
#define USER_MEM_2_MEMBER_DEFINITION
#define USER_MEM_2_MEMBER_OFFSET
#define USER_MEM_2_MEMBER_DATA
#define USER_MEM_2_ENTRIES (0)
#endif

#ifdef AMP_USER_MEMORY_3
#define GET_USER_MEM_3_MEMBER_VAR GET_USER_MEM_MEMBER_VAR(3)
#define USER_MEM_3_MEMBER_DEFINITION USER_MEM_MEMBER_DEFINITION(3)
#define USER_MEM_3_MEMBER_OFFSET USER_MEM_MEMBER_OFFSET(3)
#define USER_MEM_3_MEMBER_DATA USER_MEM_MEMBER_DATA(3)
#define USER_MEM_3_ENTRIES (1)
#else
#define GET_USER_MEM_3_MEMBER_VAR
#define USER_MEM_3_MEMBER_DEFINITION
#define USER_MEM_3_MEMBER_OFFSET
#define USER_MEM_3_MEMBER_DATA
#define USER_MEM_3_ENTRIES (0)
#endif


#define AMP_USER_MEMORY_MAX_NUM 4

#define AMP_USER_MEMORY_ENTRIES	(USER_MEM_0_ENTRIES + USER_MEM_1_ENTRIES + USER_MEM_2_ENTRIES + USER_MEM_3_ENTRIES)

#define AMP_USER_MEMORY_INTERNAL_API_DEFINITION \
	const struct fw_rsc_carveout *resource_table_get_amp_user_memory(uint32_t id) \
	{ \
		if (id >= AMP_USER_MEMORY_MAX_NUM) \
			return NULL; \
		GET_USER_MEM_0_MEMBER_VAR \
		GET_USER_MEM_1_MEMBER_VAR \
		GET_USER_MEM_2_MEMBER_VAR \
		GET_USER_MEM_3_MEMBER_VAR \
		return NULL; \
	}

const struct fw_rsc_carveout *resource_table_get_amp_user_memory(uint32_t id);

#define AMP_USER_MEMORY_MEMBERS_DEFINITION \
	USER_MEM_0_MEMBER_DEFINITION \
	USER_MEM_1_MEMBER_DEFINITION \
	USER_MEM_2_MEMBER_DEFINITION \
	USER_MEM_3_MEMBER_DEFINITION

#define AMP_USER_MEMORY_MEMBERS_OFFSET \
	USER_MEM_0_MEMBER_OFFSET \
	USER_MEM_1_MEMBER_OFFSET \
	USER_MEM_2_MEMBER_OFFSET \
	USER_MEM_3_MEMBER_OFFSET

#define AMP_USER_MEMORY_MEMBERS_DATA \
	USER_MEM_0_MEMBER_DATA \
	USER_MEM_1_MEMBER_DATA \
	USER_MEM_2_MEMBER_DATA \
	USER_MEM_3_MEMBER_DATA


/* User API */

typedef struct amp_user_memory
{
	uint32_t id;
	const char *name;

	uint32_t len;
	void *addr;
} amp_user_memory_t;

int is_amp_user_memory_exist(uint32_t id);

int get_amp_user_memory(uint32_t id, amp_user_memory_t *user_mem);
void show_amp_user_memory(uint32_t id);
void show_all_amp_user_memory(void);

#ifdef __cplusplus
}
#endif

#endif /* __AMP_USER_MEMORY_H__ */
