/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef __MQTT_CLIENT__H__
#define __MQTT_CLIENT__H__

#include "core_mqtt.h"
#include "core_mqtt_state.h"
#include "port_network.h"

#define CONNECT_WITH_TLS 0

#define BROKER_ENDPOINT                               "rtpeer.allwinnertech.com"
#define BROKER_ENDPOINT_LENGTH                        ( ( uint16_t ) ( sizeof( BROKER_ENDPOINT ) - 1 ) )

#if CONNECT_WITH_TLS
#define BROKER_PORT    ( 8883 )
#else
#define BROKER_PORT    ( 1883 )
#endif

#define KEEPALIVE_INTERVAL_MS		              ( 60U )
#define MQTT_RECONNECT_INTERVAL                       ( 300U )
#define MQTT_MAX_RECONNECT_ATTEMPTS                   ( 5U )
#define MQTT_KEEP_ALIVE_INTERVAL_SECONDS_SERVER       ( 60U )
#define CONNACK_RECV_TIMEOUT_MS                       ( 1000U )
#define OUTGOING_PUBLISH_RECORD_LEN                   ( 10U )
#define INCOMING_PUBLISH_RECORD_LEN                   ( 10U )

int mqtt_low_power_keepalive_demo(void);
int mqtt_low_power_keepalive_demo_deinit(void);

#endif
