/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _MMC_PLATFORM_H_
#define _MMC_PLATFORM_H_

#define CONFIG_RISCV

#define SUNXI_GPIO_BASE    		0x42000000
#define SUNXI_SMHC0_BASE		0x44020000
#define SUNXI_CCMU_APP_BASE		0x42001000
#define SUNXI_CCMU_AON_BASE		0x4A010000

#define CCMU_BUS_CLK_GATING1_REG		(SUNXI_CCMU_APP_BASE + 0x0084)
#define CCMU_BUS_RESET1_REG             (SUNXI_CCMU_APP_BASE + 0x0094)
#define CCMU_SDMMC0_CLK_REG             (SUNXI_CCMU_APP_BASE + 0x0014)
#define CCMU_SDMMC1_CLK_REG             (SUNXI_CCMU_APP_BASE + 0x005C)
#define CCMU_PLL_PERI0_CTRL_REG	        (SUNXI_CCMU_AON_BASE + 0x0020)

#define GPIO_POW_MODE_REG (0x0340)
#define SMHC0_BGR_REG_SMHC0_RST_OFFSET 20
#define SMHC0_BGR_REG_SMHC0_GATING_OFFSET 20

#define HOSC_CC_ID						AW_AON_CCU
#define HOSC_CLK_ID						CLK_AON_HOSC_FAKE_MUX

#include <hal_time.h>
#include <hal_clk.h>
#include <hal_cache.h>

#define sleep  hal_sleep
#define usleep hal_usleep
#define msleep hal_msleep
#define udelay hal_udelay
#define mdelay hal_mdelay
#define sdelay hal_sdelay

static inline unsigned int timer_get_us(void)
{
	return hal_get_timestamp();
}

#endif	/* _MMC_PLATFORM_H_ */
