/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef _AW_RPCFS_INTERNEL_H
#define _AW_RPCFS_INTERNEL_H

#include <rpcfs.h>
#include <srpc_func.h>
#include <hal_cache.h>
#include <hal_mem.h>
#include <sys/stat.h>
#include "rpcfs_fcntl.h"

#define RPCFS_CLASS_ID              (1)
#define RPCFS_FUNC_ID(nr)           (RPCFS_CLASS_ID << 16 | nr)

#define RPCFS_FUNC_OPEN_ID          RPCFS_FUNC_ID(0)
#define RPCFS_FUNC_CLOSE_ID         RPCFS_FUNC_ID(1)
#define RPCFS_FUNC_RW_ID            RPCFS_FUNC_ID(2)
#define RPCFS_FUNC_LINK_ID          RPCFS_FUNC_ID(3)
#define RPCFS_FUNC_UNLINK_ID        RPCFS_FUNC_ID(4)
#define RPCFS_FUNC_RENAME_ID        RPCFS_FUNC_ID(5)
#define RPCFS_FUNC_GETDENTS_ID      RPCFS_FUNC_ID(6)
#define RPCFS_FUNC_SEEKDIR_ID       RPCFS_FUNC_ID(7)
#define RPCFS_FUNC_MKDIR_ID         RPCFS_FUNC_ID(8)
#define RPCFS_FUNC_RMDIR_ID         RPCFS_FUNC_ID(9)
#define RPCFS_FUNC_STATFS_ID        RPCFS_FUNC_ID(10)
#define RPCFS_FUNC_FSTATFS_ID       RPCFS_FUNC_ID(11)
#define RPCFS_FUNC_ACCESS_ID        RPCFS_FUNC_ID(12)
#define RPCFS_FUNC_FSYNC_ID         RPCFS_FUNC_ID(13)
#define RPCFS_FUNC_TRUNCATE_ID      RPCFS_FUNC_ID(14)
#define RPCFS_FUNC_FTRUNCATE_ID     RPCFS_FUNC_ID(15)
#define RPCFS_FUNC_LSEEK_ID         RPCFS_FUNC_ID(16)
#define RPCFS_FUNC_FSTAT64_ID       RPCFS_FUNC_ID(17)
#define RPCFS_FUNC_STAT64_ID        RPCFS_FUNC_ID(18)
#define RPCFS_FUNC_GETDENTOFS_ID    RPCFS_FUNC_ID(19)

#ifdef CONFIG_COMPONENTS_RPCFS_DEBUG
#define rpcfs_dbg					printf
#else
#define rpcfs_dbg(...)				do { } while(0)
#endif
#define rpcfs_info					printf
#define rpcfs_err					printf

#define rpcfs_malloc				hal_malloc
#define rpcfs_free					hal_free
#define rpcfs_malloc_align(x)		hal_malloc_align(x, RPCFS_ARCH_CACHELINE)
#define rpcfs_free_align			hal_free_align

#define rpcfs_cache_clean(x, len)	hal_dcache_clean((unsigned long)(x), len)
#define rpcfs_cache_inval(x, len)	hal_dcache_invalidate((unsigned long)(x), len)

#define RPCFS_ARCH_CACHELINE		(64)
#define RPCFS_MAX_PATH_LEN			(128)
#define RPCFS_CACHE_BUF_SIZE		(4096)

#endif /* _AW_RPCFS_INTERNEL_H */
