/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY¡¯S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS¡¯SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY¡¯S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __TMR_SUN300IW1_H__
#define __TMR_SUN300IW1_H__

#include <hal_clk.h>
#include <hal_reset.h>
#include <sunxi_hal_common.h>

#define TIMER_CLK_CTRL_T

#define TIMER_APB1_CLK CLK_AON_HOSC_FAKE_MUX
#define TIMER_APB_CLK_TYPE HAL_SUNXI_AON_CCU

#define TIMER_CLK_ID CLK_TIMER
#define TIMER_APP_CLK_TYPE HAL_SUNXI_CCU

#define TIMER_RESET_ID RST_BUS_TIMER
#define TIMER_APP_RESET_TYPE HAL_SUNXI_RESET

#define HTIMER_APB_CLK CLK_AON_HOSC_FAKE_MUX
#define HTIMER_APB_CLK_TYPE HAL_SUNXI_AON_CCU

#define CCU_APP_TIMER (SUN300IW1_APP_CCU_BASE + 0x0080)

#define SUNXI_TMR_PBASE 0x42050000

#define SUNXI_IRQ_TMR(id) MAKE_IRQn((75 + (id)), 0)

#define SUNXI_SYS_HTIMER_BASE	0x43008000

#ifdef CONFIG_HTIMER_CLK_SOURCE_BY_TIMER
#ifdef CONFIG_HTIMER_CLK_192MHZ
#define HTIMER_CLK_DIV		(0)
#define HTIMER_CLK_BASE_VALUE	(196)
#define HTIMER_CLK_FREQ		(196000000)
#elif CONFIG_HTIMER_CLK_96MHZ
#define HTIMER_CLK_DIV		(1)
#define HTIMER_CLK_BASE_VALUE	(96)
#define HTIMER_CLK_FREQ		(96000000)
#elif CONFIG_HTIMER_CLK_64MHZ
#define HTIMER_CLK_DIV		(2)
#define HTIMER_CLK_BASE_VALUE	(64)
#define HTIMER_CLK_FREQ		(64000000)
#elif CONFIG_HTIMER_CLK_48MHZ
#define HTIMER_CLK_DIV		(4)
#define HTIMER_CLK_BASE_VALUE	(48)
#define HTIMER_CLK_FREQ		(48000000)
#endif
#else
#define HTIMER_CLK_BASE_VALUE   (192)
#define HTIMER_CLK_FREQ         (192000000)
#endif

enum {
	SUNXI_HTIMER_0 = 0,
	SUNXI_HTIMER_1,
	HTIMER_MAX_NUM
};
#define SUNXI_HTIMER_BASE(id) (SUNXI_SYS_HTIMER_BASE)
#define HTIMER_CTL_REG_OFFSET(id)	(0x20 * (id) + 0x20)
#define HTIMER_INTVAL_LO_REG_OFFSET(id)	(0x20 * (id) + 0x24)
#define HTIMER_INTVAL_HI_REG_OFFSET(id)	(0x20 * (id) + 0x28)
#define HTIMER_CNTVAL_LO_REG_OFFSET(id)	(0x20 * (id) + 0x2c)
#define HTIMER_CNTVAL_HI_REG_OFFSET(id)	(0x20 * (id) + 0x30)
#define PENDING_BIT(id)	BIT(id)
#define HTIMER_IRQ_EN(id)	BIT(id)

#define SUNXI_IRQ_HSTIMER0	MAKE_IRQn(71, 0)
#define SUNXI_IRQ_HSTIMER1	MAKE_IRQn(72, 0)

#define TIMER0_PARAMS \
{	.id = 0, \
	.reg_base = SUNXI_SYS_HTIMER_BASE, \
	.irq_num = SUNXI_IRQ_HSTIMER0, \
	.clk_type = HAL_SUNXI_CCU, .clk_id = CLK_HSTIMER, \
	.bus_type = HAL_SUNXI_CCU, .bus_id = CLK_HSTIMER, \
	.reset_type = HAL_SUNXI_RESET, .reset_id = RST_BUS_HSTIMER, \
}

#define TIMER1_PARAMS \
{	.id = 1, \
	.reg_base = SUNXI_SYS_HTIMER_BASE, \
	.irq_num = SUNXI_IRQ_HSTIMER1, \
	.clk_type = HAL_SUNXI_CCU, .clk_id = CLK_HSTIMER, \
	.bus_type = HAL_SUNXI_CCU, .bus_id = CLK_HSTIMER, \
	.reset_type = HAL_SUNXI_RESET, .reset_id = RST_BUS_HSTIMER, \
}

#endif /* __TMR_SUN300IW1_H__ */
