/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __PLATFORM_GPIO_H__
#define __PLATFORM_GPIO_H__

#ifdef __cplusplus
extern "C" {
#endif

#define SUNXI_GPIO_STANDARD

#define GPIO_MAX_BANK PL_BASE
#define BANK_BOUNDARY PL_BASE

#define SUNXI_GPIO_PBASE 0x42000000
#define SUNXI_GPIO_RES_SIZE 0x45C

#define SUNXI_GPIO_R_PBASE 0x42000540
#define SUNXI_R_GPIO_RES_SIZE 0x0058

#if defined(CONFIG_ARCH_RISCV) /* E907 */
#include <interrupt.h>
#define SUNXI_IRQ_GPIOA (MAKE_IRQn(83, 0))
#define SUNXI_IRQ_GPIOC (MAKE_IRQn(87, 0))
#define SUNXI_IRQ_GPIOD (MAKE_IRQn(89, 0))
#define SUNXI_IRQ_R_GPIOL (MAKE_IRQn(99, 0))
#endif

typedef enum
{
	GPIO_PA0 = GPIOA(0),
	GPIO_PA1 = GPIOA(1),
	GPIO_PA2 = GPIOA(2),
	GPIO_PA3 = GPIOA(3),
	GPIO_PA4 = GPIOA(4),
	GPIO_PA5 = GPIOA(5),
	GPIO_PA6 = GPIOA(6),
	GPIO_PA7 = GPIOA(7),
	GPIO_PA8 = GPIOA(8),
	GPIO_PA9 = GPIOA(9),
	GPIO_PA10 = GPIOA(10),
	GPIO_PA11 = GPIOA(11),
	GPIO_PA12 = GPIOA(12),

	GPIO_PC0 = GPIOC(0),
	GPIO_PC1 = GPIOC(1),
	GPIO_PC2 = GPIOC(2),
	GPIO_PC3 = GPIOC(3),
	GPIO_PC4 = GPIOC(4),
	GPIO_PC5 = GPIOC(5),
	GPIO_PC6 = GPIOC(6),
	GPIO_PC7 = GPIOC(7),
	GPIO_PC8 = GPIOC(8),
	GPIO_PC9 = GPIOC(9),
	GPIO_PC10 = GPIOC(10),
	GPIO_PC11 = GPIOC(11),
	GPIO_PC12 = GPIOC(12),
	GPIO_PC13 = GPIOC(13),
	GPIO_PC14 = GPIOC(14),
	GPIO_PC15 = GPIOC(15),
	GPIO_PC16 = GPIOC(16),
	GPIO_PC17 = GPIOC(17),
	GPIO_PC18 = GPIOC(18),

	GPIO_PD0 = GPIOD(0),
	GPIO_PD1 = GPIOD(1),
	GPIO_PD2 = GPIOD(2),
	GPIO_PD3 = GPIOD(3),
	GPIO_PD4 = GPIOD(4),
	GPIO_PD5 = GPIOD(5),
	GPIO_PD6 = GPIOD(6),
	GPIO_PD7 = GPIOD(7),
	GPIO_PD8 = GPIOD(8),
	GPIO_PD9 = GPIOD(9),
	GPIO_PD10 = GPIOD(10),
	GPIO_PD11 = GPIOD(11),
	GPIO_PD12 = GPIOD(12),
	GPIO_PD13 = GPIOD(13),
	GPIO_PD14 = GPIOD(14),
	GPIO_PD15 = GPIOD(15),
	GPIO_PD16 = GPIOD(16),
	GPIO_PD17 = GPIOD(17),
	GPIO_PD18 = GPIOD(18),
	GPIO_PD19 = GPIOD(19),
	GPIO_PD20 = GPIOD(20),
	GPIO_PD21 = GPIOD(21),
	GPIO_PD22 = GPIOD(22),
	GPIO_PD23 = GPIOD(23),
	GPIO_PD24 = GPIOD(24),
	GPIO_PD25 = GPIOD(25),

	GPIO_PL0 = GPIOL(0),
	GPIO_PL1 = GPIOL(1),
	GPIO_PL2 = GPIOL(2),
	GPIO_PL3 = GPIOL(3),
	GPIO_PL4 = GPIOL(4),
	GPIO_PL5 = GPIOL(5),
	GPIO_PL6 = GPIOL(6),
	GPIO_PL7 = GPIOL(7),

	/* To aviod compile warnings. */
	GPIO_MAX = GPIOO(31),

} gpio_pin_t;

#ifdef __cplusplus
}
#endif
#endif /* __PLATFORM_GPIO_H__ */
