/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __RV_CLIC_H__
#define __RV_CLIC_H__

/* RISC-V CLIC register offset */
#define CLIC_CFG_REG_OFF 0x00
#define CLIC_INFO_REG_OFF 0x04

#define CLIC_MINTTHRESH_REG_OFF 0x08

#define CLIC_INT_IP_REG_OFF 0x1000
#define CLIC_INT_IE_REG_OFF 0x1001
#define CLIC_INT_ATTR_REG_OFF 0x1002
#define CLIC_INT_CTRL_REG_OFF 0x1003

#define CLIC_INT_REG_ADDR_INTERVAL 0x4

#define CLIC_INT_X_IP_REG_OFF(id) (0x1000 + ((id) * CLIC_INT_REG_ADDR_INTERVAL))
#define CLIC_INT_X_IE_REG_OFF(id) (0x1001 + ((id) * CLIC_INT_REG_ADDR_INTERVAL))
#define CLIC_INT_X_ATTR_REG_OFF(id) (0x1002 + ((id) * CLIC_INT_REG_ADDR_INTERVAL))
#define CLIC_INT_X_CTRL_REG_OFF(id) (0x1003 + ((id) * CLIC_INT_REG_ADDR_INTERVAL))

#define CLIC_INX_X_32BIT_REG_OFF(id) (0x1000 + ((id) * CLIC_INT_REG_ADDR_INTERVAL))

/* CLIC_CFG_REG */
#define PREEMPTION_PRIORITY_BITS_SHIFT 1
#define PREEMPTION_PRIORITY_BITS_MASK (0xF << PREEMPTION_PRIORITY_BITS_SHIFT)

/* CLIC_INFO_REG */
#define IRQ_CNT_SHIFT 0
#define IRQ_CNT_MASK (0x1FFF << IRQ_CNT_SHIFT)

#define HW_VERSION_SHIFT 13
#define HW_VERSION_MASK (0xF << HW_VERSION_SHIFT)

#define HW_IMPL_VERSION_SHIFT 17
#define HW_IMPL_VERSION_MASK (0xF << HW_IMPL_VERSION_SHIFT)

#define CTRL_REG_BITS_SHIFT 21
#define CTRL_REG_BITS_MASK (0xF << CTRL_REG_BITS_SHIFT)

/* CLIC_INT_IP_REG */
#define IP_SHIFT 0
#define IP_BIT_MASK (0x1 << IP_SHIFT)

/* CLIC_INT_IE_REG */
#define IE_SHIFT 0
#define IE_BIT_MASK (0x1 << IE_SHIFT)

/* CLIC_INT_ATTR_REG */
#define HW_VECTOR_IRQ_SHIFT 0
#define HW_VECTOR_IRQ_BIT_MASK (0x1 << HW_VECTOR_IRQ_SHIFT)

#define TRIGGER_TYPE_SHIFT 1
#define TRIGGER_TYPE_BIT_MASK (0x3 << TRIGGER_TYPE_SHIFT)

/* CLIC_INT_CTRL_REG */

extern irq_controller_ops_t g_rv_clic_ops;

#if defined(CONFIG_COMPONENTS_PM)
int clic_pm_init(void *obj);
#endif
#endif /* __RV_CLIC_H__ */
