/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __SUN300IW1_APP_CCU_H__
#define __SUN300IW1_APP_CCU_H__

#define APP_CCU_REG_BASE      0x42001000

enum sun300iw1_app_ccu_clk_id
{
	CLK_APP_DRAM,
	CLK_APP_E907_TS,
	CLK_APP_AL27_MT,
	CLK_APP_SMHC0,
	CLK_APP_SS,
	CLK_APP_SPI,
	CLK_APP_SPIF,
	CLK_APP_MCSI,
	CLK_APP_CSI_MASTER0,
	CLK_APP_CSI_MASTER1,
	CLK_APP_SPI2,
	CLK_APP_TCONLCD,
	CLK_APP_DE,
	CLK_APP_G2D,
	CLK_APP_GPADC,
	CLK_APP_VE,
	CLK_APP_AUDIO_DAC,
	CLK_APP_AUDIO_ADC,
	CLK_APP_I2S0,
	CLK_APP_SMHC1,
	CLK_APP_PLL_AUDIO_4X,
	CLK_APP_PLL_AUDIO_1X,
	CLK_APP_SPI1,
	//CLK_APP_GMAC_FANOUT,
	CLK_APP_A27L2_CFG_GATE,
	CLK_APP_A27L2_MSGBOX_GATE,
	CLK_APP_USB_24M_GATE,
	CLK_APP_USB_12M_GATE,
	CLK_APP_USB_48M_GATE,
	CLK_APP_AVS_GATE,
	CLK_APP_GMAC_25M,
	CLK_APP_BUS_DPSS_GATE,
	CLK_APP_BUS_GPIO_GATE,
	CLK_APP_BUS_MCSI_AHB_GATE,
	CLK_APP_MBUS_MCSI_GATE,
	CLK_APP_BUS_VID_OUT_GATE,
	CLK_APP_MBUS_VID_OUT_GATE,
	CLK_APP_BUS_GMAC_AHB_GATE,
	CLK_APP_BUS_USB_OHCI_GATE,
	CLK_APP_BUS_USB_EHCI_GATE,
	CLK_APP_BUS_USB_OTG_GATE,
	CLK_APP_BUS_USB_GATE,
	CLK_APP_BUS_UART3_GATE,
	CLK_APP_BUS_UART2_GATE,
	CLK_APP_BUS_UART1_GATE,
	CLK_APP_BUS_UART0_GATE,
	CLK_APP_BUS_TWI0_GATE,
	CLK_APP_BUS_PWM_GATE,
	CLK_APP_BUS_TRNG_GATE,
	CLK_APP_BUS_TIMER_GATE,
	CLK_APP_BUS_SG_DMA_GATE,
	CLK_APP_BUS_DMA_GATE,
	CLK_APP_BUS_SYSCRTL_GATE,
	CLK_APP_BUS_CE_GATE,
	CLK_APP_BUS_HSTIMER_GATE,
	CLK_APP_BUS_SPLOCK_GATE,
	CLK_APP_BUS_DRAM_GATE,
	CLK_APP_BUS_E907_MSGBOX_GATE,
	CLK_APP_BUS_E907_CFG_GATE,
	CLK_APP_MBUS_G2D_GATE,
	CLK_APP_BUS_G2D_GATE,
	CLK_APP_BUS_G2D_HB_GATE,
	CLK_APP_BUS_TWI2_GATE,
	CLK_APP_BUS_TWI1_GATE,
	CLK_APP_BUS_SPI2_GATE,
	CLK_APP_BUS_GMAC_HBUS_GATE,
	CLK_APP_BUS_SMHC1_GATE,
	CLK_APP_BUS_SMHC0_GATE,
	CLK_APP_BUS_SPI1_GATE,
	CLK_APP_BUS_GBGSYS_GATE,
	CLK_APP_MBUS_GMAC_GATE,
	CLK_APP_MBUS_SMHC1_GATE,
	CLK_APP_MBUS_SMHC0_GATE,
	CLK_APP_MBUS_USB_GATE,
	CLK_APP_MBUS_SG_DMA_GATE,
	CLK_APP_BUS_I2S0_GATE,
	CLK_APP_BUS_ADDA_GATE,
	CLK_APP_BUS_SPIF_GATE,
	CLK_APP_BUS_SPI_GATE,
	CLK_APP_BUS_VE_AHB_GATE,
	CLK_APP_MBUS_VE_GATE,
	CLK_APP_BUS_THS_GATE,
	CLK_APP_BUS_GPA_GATE,
	CLK_APP_BUS_MCSI_GATE,
	CLK_APP_BUS_MCSI_SCLK_GATE,
	CLK_APP_BUS_MISP_SCLK_GATE,
	CLK_APP_BUS_RES_DCAP_24M_GATE,
	CLK_APP_BUS_SD_MONITOR_GATE,
	CLK_APP_BUS_AHB_MONITOR_GATE,
	CLK_APP_BUS_VE_SCLK_GATE,
	CLK_APP_BUS_VE_GATE,
	CLK_APP_BUS_TCON_GATE,
	CLK_APP_BUS_SG_DMA_MCLK_GATE,
	CLK_APP_BUS_DE_GATE,
	CLK_APP_BUS_DE_HB_GATE,
	CLK_APP_BT,
	CLK_APP_BUS_ASW_CLK32M_GATE,
	CLK_APP_BUS_BT_CLK32M_GATE,
	CLK_APP_BUS_BT_CLK48M_GATE,

	APP_CCU_CLK_NUMBER,
};

/* provide some legacy macro to be compatible with legacy code  */
#define CLK_DRAM CLK_APP_DRAM
#define CLK_E907_TS CLK_APP_E907_TS
#define CLK_AL27_MT CLK_APP_AL27_MT
#define CLK_SMHC0 CLK_APP_SMHC0
#define CLK_SS CLK_APP_SS
#define CLK_SPI CLK_APP_SPI
#define CLK_SPIF CLK_APP_SPIF
#define CLK_MCSI CLK_APP_MCSI
#define CLK_CSI_MASTER0 CLK_APP_CSI_MASTER0
#define CLK_CSI_MASTER1 CLK_APP_CSI_MASTER1
#define CLK_SPI2 CLK_APP_SPI2
#define CLK_TCONLCD CLK_APP_TCONLCD
#define CLK_DE CLK_APP_DE
#define CLK_G2D CLK_APP_G2D
#define CLK_GPADC0_24M CLK_APP_GPADC
#define CLK_VE CLK_APP_VE
#define CLK_AUDIO_DAC CLK_APP_AUDIO_DAC
#define CLK_AUDIO_ADC CLK_APP_AUDIO_ADC
#define CLK_I2S0 CLK_APP_I2S0
#define CLK_SMHC1 CLK_APP_SMHC1
#define CLK_PLL_AUDIO_4X CLK_APP_PLL_AUDIO_4X
#define CLK_PLL_AUDIO_1X CLK_APP_PLL_AUDIO_1X
#define CLK_SPI1 CLK_APP_SPI1
//#define CLK_A27L2_CFG_GATE CLK_APP_A27L2_CFG_GATE
#define CLK_GMAC_FANOUT CLK_APP_A27L2_CFG_GATE
#define CLK_A27L2_MSGBOX CLK_APP_A27L2_MSGBOX_GATE
#define CLK_USB_24M CLK_APP_USB_24M_GATE
#define CLK_USB_12M CLK_APP_USB_12M_GATE
#define CLK_USB_48M CLK_APP_USB_48M_GATE
#define CLK_AVS CLK_APP_AVS_GATE
#define CLK_GMAC_25M CLK_APP_GMAC_25M
#define CLK_BUS_DPSS_TOP CLK_APP_BUS_DPSS_GATE
#define CLK_BUS_GPIO CLK_APP_BUS_GPIO_GATE
#define CLK_MCSI_AHB CLK_APP_BUS_MCSI_AHB_GATE
#define CLK_MBUS_MCSI CLK_APP_MBUS_MCSI_GATE
#define CLK_VID_OUT CLK_APP_BUS_VID_OUT_GATE
#define CLK_MBUS_VID_OUT CLK_APP_MBUS_VID_OUT_GATE
#define CLK_HBUS_GMAC CLK_APP_BUS_GMAC_AHB_GATE
#define CLK_USBOHCI CLK_APP_BUS_USB_OHCI_GATE
#define CLK_USBEHCI CLK_APP_BUS_USB_EHCI_GATE
#define CLK_USBOTG CLK_APP_BUS_USB_OTG_GATE
#define CLK_USB CLK_APP_BUS_USB_GATE
#define CLK_UART3 CLK_APP_BUS_UART3_GATE
#define CLK_UART2 CLK_APP_BUS_UART2_GATE
#define CLK_UART1 CLK_APP_BUS_UART1_GATE
#define CLK_UART0 CLK_APP_BUS_UART0_GATE
#define CLK_TWI0 CLK_APP_BUS_TWI0_GATE
#define CLK_PWM CLK_APP_BUS_PWM_GATE
#define CLK_TRNG CLK_APP_BUS_TRNG_GATE
#define CLK_TIMER CLK_APP_BUS_TIMER_GATE
#define CLK_SG_DMA CLK_APP_BUS_SG_DMA_GATE
#define CLK_DMA CLK_APP_BUS_DMA_GATE
#define CLK_SYSCRTL CLK_APP_BUS_SYSCRTL_GATE
#define CLK_CE CLK_APP_BUS_CE_GATE
#define CLK_HSTIMER CLK_APP_BUS_HSTIMER_GATE
#define CLK_SPLOCK CLK_APP_BUS_SPLOCK_GATE
#define CLK_BUS_DRAM CLK_APP_BUS_DRAM_GATE
#define CLK_RV_MSGBOX CLK_APP_BUS_E907_MSGBOX_GATE
#define CLK_RISCV CLK_APP_BUS_E907_CFG_GATE
#define CLK_MBUS_G2D CLK_APP_MBUS_G2D_GATE
#define CLK_BUS_G2D CLK_APP_BUS_G2D_GATE
#define CLK_G2D_HB CLK_APP_BUS_G2D_HB_GATE
#define CLK_TWI2 CLK_APP_BUS_TWI2_GATE
#define CLK_TWI1 CLK_APP_BUS_TWI1_GATE
#define CLK_BUS_SPI2 CLK_APP_BUS_SPI2_GATE
#define CLK_BUS_GMAC CLK_APP_BUS_GMAC_HBUS_GATE
#define CLK_BUS_SMHC1 CLK_APP_BUS_SMHC1_GATE
#define CLK_BUS_SMHC0 CLK_APP_BUS_SMHC0_GATE
#define CLK_BUS_SPI1 CLK_APP_BUS_SPI1_GATE
#define CLK_GBGSYS CLK_APP_BUS_GBGSYS_GATE
#define CLK_MBUS_GMAC CLK_APP_MBUS_GMAC_GATE
#define CLK_MBUS_SMHC1 CLK_APP_MBUS_SMHC1_GATE
#define CLK_MBUS_SMHC0 CLK_APP_MBUS_SMHC0_GATE
#define CLK_MBUS_USB CLK_APP_MBUS_USB_GATE
#define CLK_MBUS_DMA CLK_APP_MBUS_SG_DMA_GATE
#define CLK_BUS_I2S0 CLK_APP_BUS_I2S0_GATE
#define CLK_BUS_ADDA CLK_APP_BUS_ADDA_GATE
#define CLK_BUS_SPIF CLK_APP_BUS_SPIF_GATE
#define CLK_BUS_SPI CLK_APP_BUS_SPI_GATE
#define CLK_BUS_VE_AHB CLK_APP_BUS_VE_AHB_GATE
#define CLK_MBUS_VE CLK_APP_MBUS_VE_GATE
#define CLK_BUS_THS CLK_APP_BUS_THS_GATE
#define CLK_GPA CLK_APP_BUS_GPA_GATE
#define CLK_HBUS_MCSI CLK_APP_BUS_MCSI_GATE
#define CLK_SBUS_MCSI CLK_APP_BUS_MCSI_SCLK_GATE
#define CLK_BUS_MISP CLK_APP_BUS_MISP_SCLK_GATE
#define CLK_24M_DCAP_RES CLK_APP_BUS_RES_DCAP_24M_GATE
#define CLK_SD_MONITOR CLK_APP_BUS_SD_MONITOR_GATE
#define CLK_AHB_MONITOR CLK_APP_BUS_AHB_MONITOR_GATE
#define CLK_SBUS_VE CLK_APP_BUS_VE_SCLK_GATE
#define CLK_HBUS_VE CLK_APP_BUS_VE_GATE
#define CLK_BUS_TCON CLK_APP_BUS_TCON_GATE
#define CLK_SGDMA CLK_APP_BUS_SG_DMA_MCLK_GATE
#define CLK_BUS_DE CLK_APP_BUS_DE_GATE
#define CLK_DE_HB CLK_APP_BUS_DE_HB_GATE

enum sun300iw1_app_ccu_rst_id
{
	RST_APP_BUS_DPSSTOP,
	RST_APP_BUS_MCSI,
	RST_APP_BUS_HRESETN_MCSI,
	RST_APP_BUS_G2D,
	RST_APP_BUS_DE,
	RST_APP_BUS_GMAC,
	RST_APP_BUS_USBPHY,
	RST_APP_BUS_USBOHCI,
	RST_APP_BUS_USBEHCI,
	RST_APP_BUS_USBOTG,
	RST_APP_BUS_USB,
	RST_APP_BUS_UART3,
	RST_APP_BUS_UART2,
	RST_APP_BUS_UART1,
	RST_APP_BUS_UART0,
	RST_APP_BUS_TWI0,
	RST_APP_BUS_PWM,
	RST_APP_BUS_TRNG,
	RST_APP_BUS_TIMER,
	RST_APP_BUS_SG_DMA,
	RST_APP_BUS_DMA,
	RST_APP_BUS_SYSCTRL,
	RST_APP_BUS_CE,
	RST_APP_BUS_HSTIMER,
	RST_APP_BUS_SPLOCK,
	RST_APP_BUS_DRAM,
	RST_APP_BUS_RV_MSGBOX,
	RST_APP_BUS_RV_SYS_APB,
	RST_APP_BUS_RV,
	RST_APP_BUS_A27_CFG,
	RST_APP_BUS_A27_MSGBOX,
	RST_APP_BUS_A27,
	RST_APP_BUS_TWI2,
	RST_APP_BUS_TWI1,
	RST_APP_BUS_SPI2,
	RST_APP_BUS_SMHC1,
	RST_APP_BUS_SMHC0,
	RST_APP_BUS_SPI1,
	RST_APP_BUS_DGBSYS,
	RST_APP_BUS_MBUS,
	RST_APP_BUS_TCONLCD,
	RST_APP_BUS_TCON,
	RST_APP_BUS_I2S0,
	RST_APP_BUS_AUDIO,
	RST_APP_BUS_SPIF,
	RST_APP_BUS_SPI,
	RST_APP_BUS_VE,
	RST_APP_BUS_THS,
	RST_APP_BUS_GPADC,
	RST_APP_BUS_A27WFG,
	RST_APP_BUS_GPIOWDG,
	RST_APP_BUS_RV_WDG,
	RST_APP_BUS_E907,
	RST_APP_BUS_BT,
	RST_APP_BUS_BT_RTC,

	APP_CCU_RST_NUMBER,
};

/* provide some legacy macro to be compatible with legacy code  */
#define RST_BUS_DPSSTOP RST_APP_BUS_DPSSTOP
#define RST_BUS_MCSI RST_APP_BUS_MCSI
#define RST_BUS_HRESETN_MCSI RST_APP_BUS_HRESETN_MCSI
#define RST_BUS_G2D RST_APP_BUS_G2D
#define RST_BUS_DE RST_APP_BUS_DE
#define RST_BUS_GMAC RST_APP_BUS_GMAC
#define RST_BUS_USBPHY RST_APP_BUS_USBPHY
#define RST_BUS_USBOHCI RST_APP_BUS_USBOHCI
#define RST_BUS_USBEHCI RST_APP_BUS_USBEHCI
#define RST_BUS_USBOTG RST_APP_BUS_USBOTG
#define RST_BUS_USB RST_APP_BUS_USB
#define RST_BUS_UART3 RST_APP_BUS_UART3
#define RST_BUS_UART2 RST_APP_BUS_UART2
#define RST_BUS_UART1 RST_APP_BUS_UART1
#define RST_BUS_UART0 RST_APP_BUS_UART0
#define RST_BUS_TWI0 RST_APP_BUS_TWI0
#define RST_BUS_PWM RST_APP_BUS_PWM
#define RST_BUS_TRNG RST_APP_BUS_TRNG
#define RST_BUS_TIMER RST_APP_BUS_TIMER
#define RST_BUS_SG_DMA RST_APP_BUS_SG_DMA
#define RST_BUS_DMA RST_APP_BUS_DMA
#define RST_BUS_SYSCTRL RST_APP_BUS_SYSCTRL
#define RST_BUS_CE RST_APP_BUS_CE
#define RST_BUS_HSTIMER RST_APP_BUS_HSTIMER
#define RST_BUS_SPLOCK RST_APP_BUS_SPLOCK
#define RST_BUS_DRAM RST_APP_BUS_DRAM
#define RST_BUS_RV_MSGBOX RST_APP_BUS_RV_MSGBOX
#define RST_BUS_RV_SYS_APB RST_APP_BUS_RV_SYS_APB
#define RST_BUS_RV RST_APP_BUS_RV
#define RST_BUS_A27_CFG RST_APP_BUS_A27_CFG
#define RST_BUS_A27_MSGBOX RST_APP_BUS_A27_MSGBOX
#define RST_BUS_A27 RST_APP_BUS_A27
#define RST_BUS_TWI2 RST_APP_BUS_TWI2
#define RST_BUS_TWI1 RST_APP_BUS_TWI1
#define RST_BUS_SPI2 RST_APP_BUS_SPI2
#define RST_BUS_SMHC1 RST_APP_BUS_SMHC1
#define RST_BUS_SMHC0 RST_APP_BUS_SMHC0
#define RST_BUS_SPI1 RST_APP_BUS_SPI1
#define RST_BUS_DGBSYS RST_APP_BUS_DGBSYS
#define RST_BUS_MBUS RST_APP_BUS_MBUS
#define RST_BUS_TCONLCD RST_APP_BUS_TCONLCD
#define RST_BUS_TCON RST_APP_BUS_TCON
#define RST_BUS_I2S0 RST_APP_BUS_I2S0
#define RST_BUS_AUDIO RST_APP_BUS_AUDIO
#define RST_BUS_SPIF RST_APP_BUS_SPIF
#define RST_BUS_SPI RST_APP_BUS_SPI
#define RST_BUS_VE RST_APP_BUS_VE
#define RST_BUS_THS RST_APP_BUS_THS
#define RST_BUS_GPADC RST_APP_BUS_GPADC
#define RST_BUS_A27WFG RST_APP_BUS_A27WFG
#define RST_BUS_GPIOWDG RST_APP_BUS_GPIOWDG
#define RST_BUS_RV_WDG RST_APP_BUS_RV_WDG
#define RST_BUS_E907 RST_APP_BUS_E907

#endif  /* __SUN300IW1_APP_CCU_H__ */
