/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __SUN300IW1_AON_CCU_H__
#define __SUN300IW1_AON_CCU_H__

#define AON_CCU_REG_BASE      0x4A010000  /* CCU_AON */

enum sun300iw1_aon_ccu_clk_id
{
	CLK_AON_CPU_PLL_PRE_DIV,
	CLK_AON_CPU_PLL,
	CLK_AON_PERI_PLL_PRE_DIV,
	CLK_AON_PERI_PLL,
	CLK_AON_PERI_PLL_POST_FIXED_MULT,
	CLK_AON_PERI_PLL_1536M_FIXED_DIV,
	CLK_AON_PERI_PLL_1024M_FIXED_DIV,
	CLK_AON_PERI_PLL_768M_FIXED_DIV,
	CLK_AON_PERI_PLL_614M_FIXED_DIV,
	CLK_AON_PERI_PLL_512M_FIXED_DIV,
	CLK_AON_PERI_PLL_384M_FIXED_DIV,
	CLK_AON_PERI_PLL_341M_FIXED_DIV,
	CLK_AON_PERI_PLL_307M_FIXED_DIV,
	CLK_AON_PERI_PLL_236M_FIXED_DIV,
	CLK_AON_PERI_PLL_219M_FIXED_DIV,
	CLK_AON_PERI_PLL_192M_FIXED_DIV,
	CLK_AON_PERI_PLL_118M_FIXED_DIV,
	CLK_AON_PERI_PLL_96M_FIXED_DIV,
	CLK_AON_PERI_PLL_48M_FIXED_DIV,
	CLK_AON_PERI_PLL_24M_FIXED_DIV,
	CLK_AON_PERI_PLL_12M_FIXED_DIV,
	CLK_AON_VIDEO_PLL_PRE_DIV,
	CLK_AON_VIDEO_PLL,
	CLK_AON_VIDEO_PLL_2X_FIXED_DIV,
	CLK_AON_VIDEO_PLL_1X_FIXED_DIV,
	CLK_AON_CSI_PLL_PRE_DIV,
	CLK_AON_CSI_PLL_INT_OUT,
	CLK_AON_CSI_PLL,
	CLK_AON_CSI_PLL_2X_FIXED_DIV,
	CLK_AON_CSI_PLL_1X_FIXED_DIV,
	CLK_AON_DIV32K_HALF,
	CLK_AON_HOSC_DIV_32K,
	CLK_AON_DDR_PLL_PRE_DIV,
	CLK_AON_DDR_PLL,
	CLK_AON_DDR_PLL_POST_DIV,
	CLK_AON_HOSC_FAKE_MUX,
	CLK_AON_AHB,
	CLK_AON_APB,
	CLK_AON_APB_RTC,
	CLK_AON_BUS_PWRCTRL_GATE,
	CLK_AON_BUS_RCCAL_GATE,
	CLK_AON_APB_SPC,
	CLK_AON_E907,
	CLK_AON_A27L2,

	AON_CCU_CLK_NUMBER,
};

/* provide some legacy macro to be compatible with legacy code  */
#define CLK_PLL_CPU CLK_AON_CPU_PLL
#define CLK_PLL_DDR CLK_AON_DDR_PLL
#define CLK_PLL_PERI_PARENT CLK_AON_PERI_PLL
#define CLK_PLL_PERI_CKO_1536M CLK_AON_PERI_PLL_1536M_FIXED_DIV
#define CLK_PLL_PERI_CKO_1024M CLK_AON_PERI_PLL_1024M_FIXED_DIV
#define CLK_PLL_PERI_CKO_768M CLK_AON_PERI_PLL_768M_FIXED_DIV
#define CLK_PLL_PERI_CKO_614M CLK_AON_PERI_PLL_614M_FIXED_DIV
#define CLK_PLL_PERI_CKO_512M CLK_AON_PERI_PLL_512M_FIXED_DIV
#define CLK_PLL_PERI_CKO_384M CLK_AON_PERI_PLL_384M_FIXED_DIV
#define CLK_PLL_PERI_CKO_341M CLK_AON_PERI_PLL_341M_FIXED_DIV
#define CLK_PLL_PERI_CKO_307M CLK_AON_PERI_PLL_307M_FIXED_DIV
#define CLK_PLL_PERI_CKO_236M CLK_AON_PERI_PLL_236M_FIXED_DIV
#define CLK_PLL_PERI_CKO_219M CLK_AON_PERI_PLL_219M_FIXED_DIV
#define CLK_PLL_PERI_CKO_192M CLK_AON_PERI_PLL_192M_FIXED_DIV
#define CLK_PLL_PERI_CKO_118M CLK_AON_PERI_PLL_118M_FIXED_DIV
#define CLK_PLL_PERI_CKO_96M CLK_AON_PERI_PLL_96M_FIXED_DIV
#define CLK_PLL_PERI_CKO_48M CLK_AON_PERI_PLL_48M_FIXED_DIV
#define CLK_PLL_PERI_CKO_24M CLK_AON_PERI_PLL_24M_FIXED_DIV
#define CLK_PLL_PERI_CKO_12M CLK_AON_PERI_PLL_12M_FIXED_DIV
#define CLK_PLL_VIDEO_4X CLK_AON_VIDEO_PLL
#define CLK_PLL_VIDEO_2X CLK_AON_VIDEO_PLL_2X_FIXED_DIV
#define CLK_PLL_VIDEO_1X CLK_AON_VIDEO_PLL_1X_FIXED_DIV
#define CLK_PLL_CSI_4X CLK_AON_CSI_PLL
#define CLK_PLL_CSI_2X CLK_AON_CSI_PLL_2X_FIXED_DIV
#define CLK_PLL_CSI_1X CLK_AON_CSI_PLL_1X_FIXED_DIV
#define CLK_DCXO CLK_AON_HOSC_FAKE_MUX
#define CLK_AHB CLK_AON_AHB
#define CLK_APB0 CLK_AON_APB
#define CLK_RTC_APB CLK_AON_APB_RTC
#define CLK_PWRCTRL CLK_AON_BUS_PWRCTRL_GATE
#define CLK_TCCAL CLK_AON_BUS_RCCAL_GATE
#define CLK_APB_SPC CLK_AON_APB_SPC
#define CLK_E907 CLK_AON_E907
#define CLK_A27L2 CLK_AON_A27L2

enum sun300iw1_aon_ccu_rst_id
{
	RST_AON_BUS_WLAN,
	AON_CCU_RST_NUMBER,
};

/* provide some legacy macro to be compatible with legacy code  */
#define RST_BUS_WLAN RST_AON_BUS_WLAN

#endif
