/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#include "sun300iw1_src_ccu.h"

#include "clk_source.h"

static CLK_SOURCE(g_unknown_clk, "unknown", 999999999);
static CLK_SOURCE(g_useless_clk, "useless", 123456789);
static CLK_SOURCE(g_hosc_24m_clk, "hosc-24M", 24000000);
static CLK_SOURCE(g_hosc_40m_clk, "hosc-40M", 40000000);
static CLK_SOURCE(g_losc_clk, "losc", 32768);
static CLK_SOURCE(g_rc_lf_clk, "rc-lf", 1000000);
static CLK_SOURCE(g_rc_hf_clk, "rc-hf", 16000000);
static CLK_SOURCE(g_rccal_32k_clk, "rccal_32k", 32000);
static CLK_SOURCE(g_xo32k_clk, "xo32k_32k", 32000);
static CLK_SOURCE(g_rc_freq_base_clk, "rc_fcr_base", 1);

static struct clk_hw *g_sun300iw1_src_clk_hws[] =
{
	CLK_HW_ELEMENT(CLK_SRC_UNKNOWN, g_unknown_clk),
	CLK_HW_ELEMENT(CLK_SRC_USELESS, g_useless_clk),
	CLK_HW_ELEMENT(CLK_SRC_HOSC_24M, g_hosc_24m_clk),
	CLK_HW_ELEMENT(CLK_SRC_HOSC_40M, g_hosc_40m_clk),
	CLK_HW_ELEMENT(CLK_SRC_LOSC, g_losc_clk),
	CLK_HW_ELEMENT(CLK_SRC_RC_LF, g_rc_lf_clk),
	CLK_HW_ELEMENT(CLK_SRC_RC_HF, g_rc_hf_clk),
	CLK_HW_ELEMENT(CLK_SRC_RCCAL_32K, g_rccal_32k_clk),
	CLK_HW_ELEMENT(CLK_SRC_XO32K, g_xo32k_clk),
	CLK_HW_ELEMENT(CLK_SRC_RC_FREQ_BASE, g_rc_freq_base_clk),
};

clk_controller_t g_src_ccu =
{
	.id = AW_SRC_CCU,
	.reg_base = 0,

	.clk_num = ARRAY_SIZE(g_sun300iw1_src_clk_hws),
	.clk_hws = g_sun300iw1_src_clk_hws,

	.reset_num = 0,
	.reset_hws = NULL,

	.ops = NULL,
};

