/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __MSGBOX_SUN55IW6_H
#define __MSGBOX_SUN55IW6_H

#include <hal_clk.h>

#define MSGBOX_ARM           0
#define MSGBOX_ARM_BASE      0x03003000

#define MSGBOX_CPUS          1
#define MSGBOX_CPUS_BASE     0x07094000

#define MSGBOX_RISCV         2
#define MSGBOX_RISCV_BASE    0x01a06000

#if defined(CONFIG_ARCH_ARM)
#define MSGBOX_CORE0         0
#define MSGBOX_CORE0_BASE    0x03600000

#define MSGBOX_CORE1         1
#define MSGBOX_CORE1_BASE    0x03601000

#define MSGBOX_CORE2         2
#define MSGBOX_CORE2_BASE    0x03602000

#define MSGBOX_CORE3         3
#define MSGBOX_CORE3_BASE    0x03603000
#endif

/* DSP does not exist, this configuration is to solve compilation errors */
#define MSGBOX_DSP           -1
#define MSGBOX_DSP_BASE      -1

#if defined(CONFIG_ARCH_RISCV)
#define MBOX_BGR_REG         0x0200276c
#define THIS_MSGBOX_USE      MSGBOX_RISCV
#define R_MBOX_RST           (0x1 << 16)
#define R_MBOX_GATINGA       (0x1)
#define IRQ_MSGBOX           MAKE_IRQn(200, 0)
#define IRQ_WR_MSGBOX        MAKE_IRQn(240, 0)
#define RST_MSGBOX_TYPE      HAL_SUNXI_RESET
#define RST_MSGBOX           RST_BUS_MSGBOX_RV
#define CLK_MSGBOX_TYPE      HAL_SUNXI_CCU
#define CLK_MSGBOX           CLK_MSGBOX_RV
/* CONFIG_ARCH_RISCV */
#elif defined(CONFIG_ARCH_ARM)
#define MBOX_BGR_REG         0x02002764
#define THIS_MSGBOX_USE      MSGBOX_CORE3
#define R_MBOX_RST           (0x1 << 16)
#define R_MBOX_GATINGA       (0x1)
#define IRQ_MSGBOX           (201)
//#define IRQ_WR_MSGBOX      MAKE_IRQn(240, 0)
#define RST_MSGBOX_TYPE      HAL_SUNXI_RESET
#define RST_MSGBOX           RST_BUS_MSGBOX_CORE3
#define CLK_MSGBOX_TYPE      HAL_SUNXI_CCU
#define CLK_MSGBOX           CLK_MSGBOX_CORE3
#endif /* CONFIG_ARCH_ARM */

#endif  /* __MSGBOX_SUN55IW6_H */
