/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/* this file is generate by ./mk_event_def.sh, should not be modify directly */
#include <stdio.h>
#include "include/trace_event.h"

struct subsys_entry subsys_class[EV_NUM_SUBSYS] = {
	[EV_SYS] = {
		.name = EV_SYS_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SYS_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SYS)
	},
	[EV_RT_SYS] = {
		.name = EV_RT_SYS_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RT_SYS_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RT_SYS)
	},
	[EV_TICK] = {
		.name = EV_TICK_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_TICK_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_TICK)
	},
	[EV_IRQ] = {
		.name = EV_IRQ_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_IRQ_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_IRQ)
	},
	[EV_MEM] = {
		.name = EV_MEM_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_MEM_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_MEM)
	},
	[EV_SCHE] = {
		.name = EV_SCHE_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SCHE_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SCHE)
	},
	[EV_RT_TMR] = {
		.name = EV_RT_TMR_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RT_TMR_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RT_TMR)
	},
	[EV_MUTEX] = {
		.name = EV_MUTEX_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_MUTEX_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_MUTEX)
	},
	[EV_SPIN] = {
		.name = EV_SPIN_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SPIN_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SPIN)
	},
	[EV_SEM] = {
		.name = EV_SEM_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SEM_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SEM)
	},
	[EV_RT_NOTIFY] = {
		.name = EV_RT_NOTIFY_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RT_NOTIFY_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RT_NOTIFY)
	},
	[EV_QUEUE] = {
		.name = EV_QUEUE_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_QUEUE_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_QUEUE)
	},
	[EV_RT_QUEUE] = {
		.name = EV_RT_QUEUE_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RT_QUEUE_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RT_QUEUE)
	},
	[EV_FS] = {
		.name = EV_FS_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_FS_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_FS)
	},
	[EV_FATFS] = {
		.name = EV_FATFS_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_FATFS_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_FATFS)
	},
	[EV_NTFS] = {
		.name = EV_NTFS_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_NTFS_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_NTFS)
	},
	[EV_OPENAMP] = {
		.name = EV_OPENAMP_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_OPENAMP_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_OPENAMP)
	},
	[EV_SUNXIAMP] = {
		.name = EV_SUNXIAMP_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SUNXIAMP_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_SUNXIAMP)
	},
	[EV_USR0] = {
		.name = EV_USR0_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_USR0_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_USR0)
	},
	[EV_RPD] = {
		.name = EV_RPD_STRING,
		.enable = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RPD_DEFAULT),
		.buildin = EV_MACRO_IS_ENABLED(CONFIG_EVENTS_TRACE_EV_RPD)
	},
};
